// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_media_upload_mediaSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        owner_type: {
            type: 'string',
            title: 'Owner Type',
            default: 'product'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_media-upload_media'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate',
    description: 'Fields accepted when creating a category.'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'id', 'store_id'],
    title: 'CategoryPublic',
    description: 'Public representation of a category.'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CategoryUpdate',
    description: 'Partial update for a category.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageAttachSchema = {
    properties: {
        media_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media File Id'
        },
        position: {
            type: 'integer',
            minimum: 0,
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['media_file_id'],
    title: 'ImageAttach',
    description: 'Link a (processed) media file to a product at a position.'
} as const;

export const ImagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        media_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media File Id'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        variants: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variants'
        },
        status: {
            '$ref': '#/components/schemas/MediaStatus'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'product_id', 'media_file_id', 'position', 'url', 'variants', 'status'],
    title: 'ImagePublic',
    description: "Public representation of a product image (with its media's URL/status)."
} as const;

export const InventoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        variant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variant Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'product_id', 'variant_id', 'quantity'],
    title: 'InventoryPublic',
    description: 'Public representation of a stock entry.'
} as const;

export const InventorySetSchema = {
    properties: {
        variant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variant Id'
        },
        quantity: {
            type: 'integer',
            minimum: 0,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['quantity'],
    title: 'InventorySet',
    description: 'Set the stock quantity for a product (optionally a specific variant).'
} as const;

export const MediaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        owner_type: {
            type: 'string',
            title: 'Owner Type'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        variants: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variants'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        status: {
            '$ref': '#/components/schemas/MediaStatus'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'owner_type', 'owner_id', 'key', 'url', 'variants', 'content_type', 'size', 'status'],
    title: 'MediaPublic',
    description: 'Public representation of an uploaded media file.'
} as const;

export const MediaStatusSchema = {
    type: 'string',
    enum: ['processing', 'ready', 'failed'],
    title: 'MediaStatus',
    description: 'Processing status of an uploaded media file.'
} as const;

export const MembershipStatusSchema = {
    type: 'string',
    enum: ['invited', 'active', 'removed'],
    title: 'MembershipStatus',
    description: 'Lifecycle status of a store membership.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const MyMembershipSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['role', 'permissions'],
    title: 'MyMembership',
    description: "The current user's role and permissions in the active store."
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Password-reset payload (token + new password).'
} as const;

export const Page_CategoryPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[CategoryPublic]'
} as const;

export const Page_ProductPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[ProductPublic]'
} as const;

export const Page_StoreMemberPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StoreMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[StoreMemberPublic]'
} as const;

export const Page_StorePublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StorePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[StorePublic]'
} as const;

export const Page_VariantPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VariantPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[VariantPublic]'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate',
    description: 'Request body for creating a user through the private endpoint.'
} as const;

export const ProductCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Price Amount Minor'
        },
        price_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Currency'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'price_amount_minor'],
    title: 'ProductCreate',
    description: 'Fields accepted when creating a product (status starts as ``draft``).'
} as const;

export const ProductPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/ProductStatus',
            default: 'draft'
        },
        price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Price Amount Minor',
            description: 'Price in minor units (INV-D4)'
        },
        price_currency: {
            type: 'string',
            maxLength: 3,
            title: 'Price Currency',
            description: 'ISO 4217 currency code'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'price_amount_minor', 'price_currency', 'id', 'store_id'],
    title: 'ProductPublic',
    description: 'Public representation of a product.'
} as const;

export const ProductStatusSchema = {
    type: 'string',
    enum: ['draft', 'published', 'archived'],
    title: 'ProductStatus',
    description: `Lifecycle status of a catalog product (doc 09).

- \`\`draft\`\`: never published; editable; the slug follows the name.
- \`\`published\`\`: live on the storefront; the slug is fixed.
- \`\`archived\`\`: taken offline but kept — reversible via publish; the slug
  stays reserved.

Deleting a product is a **soft delete** (\`\`deleted_at\`\`), not a status.`
} as const;

export const ProductUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Amount Minor'
        },
        price_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Currency'
        },
        is_featured: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Featured'
        }
    },
    type: 'object',
    title: 'ProductUpdate',
    description: 'Partial update for a product (unset fields are left unchanged).'
} as const;

export const ProductVariantStatusSchema = {
    type: 'string',
    enum: ['active', 'archived'],
    title: 'ProductVariantStatus',
    description: 'Lifecycle status of a product variant.'
} as const;

export const StoreCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Currency'
        },
        locale: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 35
                },
                {
                    type: 'null'
                }
            ],
            title: 'Locale'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'StoreCreate',
    description: 'Payload to create a store (slug/currency/locale default from platform).'
} as const;

export const StoreMemberInviteSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            maxLength: 50,
            title: 'Role'
        }
    },
    type: 'object',
    required: ['email', 'role'],
    title: 'StoreMemberInvite',
    description: 'Payload to invite a member by email with a role.'
} as const;

export const StoreMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        status: {
            '$ref': '#/components/schemas/MembershipStatus'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'email', 'role', 'status'],
    title: 'StoreMemberPublic',
    description: 'A store member as returned via the API.'
} as const;

export const StoreMemberRoleUpdateSchema = {
    properties: {
        role: {
            type: 'string',
            maxLength: 50,
            title: 'Role'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'StoreMemberRoleUpdate',
    description: "Payload to change a member's role."
} as const;

export const StorePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        status: {
            '$ref': '#/components/schemas/StoreStatus',
            default: 'draft'
        },
        currency: {
            type: 'string',
            maxLength: 3,
            title: 'Currency',
            description: 'ISO 4217 currency code'
        },
        locale: {
            type: 'string',
            maxLength: 35,
            title: 'Locale'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'currency', 'locale', 'id'],
    title: 'StorePublic',
    description: 'Store as returned via the API.'
} as const;

export const StoreSettingsPublicSchema = {
    properties: {
        public_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        whatsapp_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Number'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        social_links: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Social Links'
        }
    },
    type: 'object',
    required: ['id', 'store_id'],
    title: 'StoreSettingsPublic',
    description: 'Store settings as returned via the API.'
} as const;

export const StoreSettingsUpdateSchema = {
    properties: {
        public_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        whatsapp_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Number'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        social_links: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Social Links'
        }
    },
    type: 'object',
    title: 'StoreSettingsUpdate',
    description: 'Editable store settings (all optional).'
} as const;

export const StoreStatusSchema = {
    type: 'string',
    enum: ['draft', 'active', 'paused', 'suspended', 'blocked'],
    title: 'StoreStatus',
    description: `Lifecycle status of a store (doc 09).

- \`\`draft\`\`: created, not yet published (not served on the storefront).
- \`\`active\`\`: published/live — the only status the storefront serves.
- \`\`paused\`\`: taken offline by the merchant (reversible via publish).
- \`\`suspended\`\`/\`\`blocked\`\`: turned off by the platform (Fase 7); the
  dashboard guard blocks access.

Removing a store is a **soft delete** (\`\`deleted_at\`\`), never a status.`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JSON payload containing an access token.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Self password-change payload.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Payload to create an account user.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'Account user as returned via the API.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Self-registration payload.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Admin update payload (all fields optional).'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Self profile-update payload.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Paginated list of account users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VariantCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        attributes: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attributes'
        },
        price_override_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Amount Minor'
        },
        price_override_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Currency'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'VariantCreate',
    description: 'Fields accepted when creating a product variant.'
} as const;

export const VariantPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        attributes: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attributes'
        },
        price_override_amount_minor: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Amount Minor'
        },
        price_override_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Currency'
        },
        status: {
            '$ref': '#/components/schemas/ProductVariantStatus'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'product_id', 'name', 'sku', 'attributes', 'price_override_amount_minor', 'price_override_currency', 'status'],
    title: 'VariantPublic',
    description: 'Public representation of a product variant.'
} as const;

export const VariantUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        attributes: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attributes'
        },
        price_override_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Amount Minor'
        },
        price_override_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Currency'
        }
    },
    type: 'object',
    title: 'VariantUpdate',
    description: 'Partial update for a product variant.'
} as const;