// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { HealthHealthResponse, HealthHealthRedisResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, StoresCreateStoreData, StoresCreateStoreResponse, StoresListMyStoresData, StoresListMyStoresResponse, StoresGetStoreData, StoresGetStoreResponse, StoresGetMyMembershipData, StoresGetMyMembershipResponse, StoresGetStoreSettingsData, StoresGetStoreSettingsResponse, StoresUpdateStoreSettingsData, StoresUpdateStoreSettingsResponse, StoresPublishStoreData, StoresPublishStoreResponse, StoresPauseStoreData, StoresPauseStoreResponse, StoresListStoreMembersData, StoresListStoreMembersResponse, StoresInviteStoreMemberData, StoresInviteStoreMemberResponse, StoresUpdateStoreMemberRoleData, StoresUpdateStoreMemberRoleResponse, StoresRemoveStoreMemberData, StoresRemoveStoreMemberResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class HealthService {
    /**
     * Health
     * Liveness check confirming the app process is up.
     *
     * Returns:
     * A small JSON payload ``{"status": "ok"}``.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static health(): CancelablePromise<HealthHealthResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health'
        });
    }
    
    /**
     * Health Redis
     * Readiness check for Redis.
     *
     * PINGs the Redis server; raises (HTTP 500) if it is unreachable.
     *
     * Returns:
     * A small JSON payload ``{"status": "ok"}`` when Redis responds.
     * @returns string Successful Response
     * @throws ApiError
     */
    public static healthRedis(): CancelablePromise<HealthHealthRedisResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/health/redis'
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * Log in via OAuth2 and return an access token for future requests.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Validate the current access token and return the authenticated user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Start password recovery: email a reset link if the account exists.
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset a password using a valid reset token.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * Return the password-recovery email HTML for preview (superuser only).
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user directly, without authentication (local only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class StoresService {
    /**
     * Create Store
     * Create a store; the caller becomes its owner (+ subdomain).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns StorePublic Successful Response
     * @throws ApiError
     */
    public static createStore(data: StoresCreateStoreData): CancelablePromise<StoresCreateStoreResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/stores/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List My Stores
     * List the stores the current user is an active member of.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns Page_StorePublic_ Successful Response
     * @throws ApiError
     */
    public static listMyStores(data: StoresListMyStoresData = {}): CancelablePromise<StoresListMyStoresResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/stores/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Store
     * Get a store the current user can access.
     * @param data The data for the request.
     * @param data.storeId
     * @returns StorePublic Successful Response
     * @throws ApiError
     */
    public static getStore(data: StoresGetStoreData): CancelablePromise<StoresGetStoreResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/stores/{store_id}',
            path: {
                store_id: data.storeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get My Membership
     * Return the current user's role and permissions in the active store.
     * @param data The data for the request.
     * @param data.storeId
     * @returns MyMembership Successful Response
     * @throws ApiError
     */
    public static getMyMembership(data: StoresGetMyMembershipData): CancelablePromise<StoresGetMyMembershipResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/stores/{store_id}/me',
            path: {
                store_id: data.storeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Store Settings
     * Get the store's settings (requires ``settings.view``).
     * @param data The data for the request.
     * @param data.storeId
     * @returns StoreSettingsPublic Successful Response
     * @throws ApiError
     */
    public static getStoreSettings(data: StoresGetStoreSettingsData): CancelablePromise<StoresGetStoreSettingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/stores/{store_id}/settings',
            path: {
                store_id: data.storeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Store Settings
     * Update the store's settings (requires ``settings.update``).
     * @param data The data for the request.
     * @param data.storeId
     * @param data.requestBody
     * @returns StoreSettingsPublic Successful Response
     * @throws ApiError
     */
    public static updateStoreSettings(data: StoresUpdateStoreSettingsData): CancelablePromise<StoresUpdateStoreSettingsResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/stores/{store_id}/settings',
            path: {
                store_id: data.storeId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Publish Store
     * Publish the store (status active; requires ``settings.update``).
     * @param data The data for the request.
     * @param data.storeId
     * @returns StorePublic Successful Response
     * @throws ApiError
     */
    public static publishStore(data: StoresPublishStoreData): CancelablePromise<StoresPublishStoreResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/stores/{store_id}/publish',
            path: {
                store_id: data.storeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Pause Store
     * Pause the store (status paused; requires ``settings.update``).
     * @param data The data for the request.
     * @param data.storeId
     * @returns StorePublic Successful Response
     * @throws ApiError
     */
    public static pauseStore(data: StoresPauseStoreData): CancelablePromise<StoresPauseStoreResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/stores/{store_id}/pause',
            path: {
                store_id: data.storeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Store Members
     * List the store's members (requires ``team.view``).
     * @param data The data for the request.
     * @param data.storeId
     * @param data.skip
     * @param data.limit
     * @returns Page_StoreMemberPublic_ Successful Response
     * @throws ApiError
     */
    public static listStoreMembers(data: StoresListStoreMembersData): CancelablePromise<StoresListStoreMembersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/stores/{store_id}/members',
            path: {
                store_id: data.storeId
            },
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Invite Store Member
     * Invite an existing account user to the store (requires ``team.invite``).
     * @param data The data for the request.
     * @param data.storeId
     * @param data.requestBody
     * @returns StoreMemberPublic Successful Response
     * @throws ApiError
     */
    public static inviteStoreMember(data: StoresInviteStoreMemberData): CancelablePromise<StoresInviteStoreMemberResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/stores/{store_id}/members',
            path: {
                store_id: data.storeId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Store Member Role
     * Change a member's role (requires ``team.update_role``).
     * @param data The data for the request.
     * @param data.storeId
     * @param data.userId
     * @param data.requestBody
     * @returns StoreMemberPublic Successful Response
     * @throws ApiError
     */
    public static updateStoreMemberRole(data: StoresUpdateStoreMemberRoleData): CancelablePromise<StoresUpdateStoreMemberRoleResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/stores/{store_id}/members/{user_id}',
            path: {
                store_id: data.storeId,
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Remove Store Member
     * Remove (soft-delete) a member (requires ``team.remove``).
     * @param data The data for the request.
     * @param data.storeId
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static removeStoreMember(data: StoresRemoveStoreMemberData): CancelablePromise<StoresRemoveStoreMemberResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/stores/{store_id}/members/{user_id}',
            path: {
                store_id: data.storeId,
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve a paginated list of users (superuser only).
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create a new user (superuser only).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Return the authenticated user's own profile.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete the authenticated user's own account.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update the authenticated user's own profile.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update the authenticated user's own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Register a new user without authentication (public signup).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Return a user by id (own profile, or any user for superusers).
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user by id (superuser only).
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user by id (superuser only).
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Send a test email to the given address (superuser only).
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * Return ``True`` to confirm the API is reachable.
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}