// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Lifecycle status of a store membership.
 */
export type MembershipStatus = 'invited' | 'active' | 'removed';

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * The current user's role and permissions in the active store.
 */
export type MyMembership = {
    role: string;
    permissions: Array<(string)>;
};

/**
 * Password-reset payload (token + new password).
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

export type Page_StoreMemberPublic_ = {
    data: Array<StoreMemberPublic>;
    count: number;
};

export type Page_StorePublic_ = {
    data: Array<StorePublic>;
    count: number;
};

/**
 * Request body for creating a user through the private endpoint.
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Payload to create a store (slug/currency/locale default from platform).
 */
export type StoreCreate = {
    name: string;
    slug?: (string | null);
    currency?: (string | null);
    locale?: (string | null);
};

/**
 * Payload to invite a member by email with a role.
 */
export type StoreMemberInvite = {
    email: string;
    role: string;
};

/**
 * A store member as returned via the API.
 */
export type StoreMemberPublic = {
    id: string;
    user_id: string;
    email: string;
    role: string;
    status: MembershipStatus;
};

/**
 * Payload to change a member's role.
 */
export type StoreMemberRoleUpdate = {
    role: string;
};

/**
 * Store as returned via the API.
 */
export type StorePublic = {
    name: string;
    slug: string;
    status?: StoreStatus;
    /**
     * ISO 4217 currency code
     */
    currency: string;
    locale: string;
    id: string;
};

/**
 * Store settings as returned via the API.
 */
export type StoreSettingsPublic = {
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    contact_email?: (string | null);
    contact_phone?: (string | null);
    whatsapp_number?: (string | null);
    address?: (string | null);
    is_published?: boolean;
    id: string;
    store_id: string;
    social_links?: ({
    [key: string]: (string);
} | null);
};

/**
 * Editable store settings (all optional).
 */
export type StoreSettingsUpdate = {
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    contact_email?: (string | null);
    contact_phone?: (string | null);
    whatsapp_number?: (string | null);
    address?: (string | null);
    social_links?: ({
    [key: string]: (string);
} | null);
};

/**
 * Lifecycle status of a store (doc 09).
 */
export type StoreStatus = 'draft' | 'active' | 'paused' | 'suspended' | 'blocked' | 'archived';

/**
 * JSON payload containing an access token.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Self password-change payload.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Payload to create an account user.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Account user as returned via the API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * Self-registration payload.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Paginated list of account users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Admin update payload (all fields optional).
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Self profile-update payload.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type HealthHealthRedisResponse = ({
    [key: string]: (string);
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type StoresCreateStoreData = {
    requestBody: StoreCreate;
};

export type StoresCreateStoreResponse = (StorePublic);

export type StoresListMyStoresData = {
    limit?: number;
    skip?: number;
};

export type StoresListMyStoresResponse = (Page_StorePublic_);

export type StoresGetStoreData = {
    storeId: string;
};

export type StoresGetStoreResponse = (StorePublic);

export type StoresGetMyMembershipData = {
    storeId: string;
};

export type StoresGetMyMembershipResponse = (MyMembership);

export type StoresUpdateStoreSettingsData = {
    requestBody: StoreSettingsUpdate;
    storeId: string;
};

export type StoresUpdateStoreSettingsResponse = (StoreSettingsPublic);

export type StoresPublishStoreData = {
    storeId: string;
};

export type StoresPublishStoreResponse = (StorePublic);

export type StoresPauseStoreData = {
    storeId: string;
};

export type StoresPauseStoreResponse = (StorePublic);

export type StoresListStoreMembersData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type StoresListStoreMembersResponse = (Page_StoreMemberPublic_);

export type StoresInviteStoreMemberData = {
    requestBody: StoreMemberInvite;
    storeId: string;
};

export type StoresInviteStoreMemberResponse = (StoreMemberPublic);

export type StoresUpdateStoreMemberRoleData = {
    requestBody: StoreMemberRoleUpdate;
    storeId: string;
    userId: string;
};

export type StoresUpdateStoreMemberRoleResponse = (StoreMemberPublic);

export type StoresRemoveStoreMemberData = {
    storeId: string;
    userId: string;
};

export type StoresRemoveStoreMemberResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);