"""Canonical store permission catalog and the role -> permission map (doc 08).

Single source of truth, transcribed exactly from doc 08. Used to seed the
``store_permissions`` and ``store_role_permissions`` tables (via ``init_db``).
The map is **positive**: a role grants only the permissions listed for it.
"""

# Full catalog of store permissions (the owner holds all of them).
PERMISSIONS: list[str] = [
    "dashboard.view",
    "catalog.view",
    "catalog.product.view",
    "catalog.product.create",
    "catalog.product.update",
    "catalog.product.delete",
    "catalog.inventory.update",
    "catalog.category.manage",
    "catalog.product_customization.update",
    "customization.view",
    "customization.sessions.view",
    "customization.files.download",
    "customization.production_status.update",
    "customization.models.assign",
    "orders.view",
    "orders.update_status",
    "orders.cancel",
    "orders.refund",
    "orders.add_note",
    "orders.export",
    "customers.view",
    "customers.update",
    "customers.export",
    "customers.delete",
    "checkout.view",
    "checkout.update",
    "checkout.policies.update",
    "payments.view",
    "payments.connect_account",
    "payments.update_methods",
    "payments.view_transactions",
    "payments.manage_refunds",
    "layout.view",
    "layout.preview",
    "layout.update",
    "layout.assets.update",
    "shipping.view",
    "shipping.create",
    "shipping.update",
    "shipping.delete",
    "shipping.private_delivery.update",
    "discounts.view",
    "discounts.create",
    "discounts.update",
    "discounts.delete",
    "reports.view",
    "reports.export",
    "reports.financial.view",
    "domains.view",
    "domains.create",
    "domains.update",
    "domains.verify",
    "domains.delete",
    "team.view",
    "team.invite",
    "team.update_role",
    "team.remove",
    "billing.view",
    "billing.update_plan",
    "billing.view_invoices",
    "settings.view",
    "settings.update",
    "settings.delete_store",
]

# Positive role -> permission map (doc 08). Owner holds the full catalog.
ROLE_PERMISSIONS: dict[str, set[str]] = {
    "owner": set(PERMISSIONS),
    "admin": {
        "dashboard.view",
        "catalog.view",
        "catalog.product.view",
        "catalog.product.create",
        "catalog.product.update",
        "catalog.product.delete",
        "catalog.inventory.update",
        "catalog.category.manage",
        "catalog.product_customization.update",
        "customization.view",
        "customization.sessions.view",
        "customization.files.download",
        "customization.production_status.update",
        "customization.models.assign",
        "orders.view",
        "orders.update_status",
        "orders.cancel",
        "orders.add_note",
        "orders.export",
        "customers.view",
        "customers.update",
        "customers.export",
        "checkout.view",
        "checkout.update",
        "checkout.policies.update",
        "payments.view",
        "payments.update_methods",
        "payments.view_transactions",
        "layout.view",
        "layout.preview",
        "layout.update",
        "layout.assets.update",
        "shipping.view",
        "shipping.create",
        "shipping.update",
        "shipping.delete",
        "shipping.private_delivery.update",
        "discounts.view",
        "discounts.create",
        "discounts.update",
        "discounts.delete",
        "reports.view",
        "reports.export",
        "domains.view",
        "domains.create",
        "domains.update",
        "domains.verify",
        "team.view",
        "team.invite",
        "team.update_role",
        "billing.view",
        "billing.view_invoices",
        "settings.view",
        "settings.update",
    },
    "manager": {
        "dashboard.view",
        "catalog.view",
        "catalog.product.view",
        "catalog.product.create",
        "catalog.product.update",
        "catalog.inventory.update",
        "catalog.category.manage",
        "customization.view",
        "customization.sessions.view",
        "customization.files.download",
        "customization.production_status.update",
        "orders.view",
        "orders.update_status",
        "orders.add_note",
        "orders.export",
        "customers.view",
        "customers.update",
        "customers.export",
        "checkout.view",
        "payments.view",
        "payments.view_transactions",
        "shipping.view",
        "discounts.view",
        "discounts.create",
        "discounts.update",
        "reports.view",
        "reports.export",
        "settings.view",
    },
    "support": {
        "dashboard.view",
        "customization.view",
        "customization.sessions.view",
        "orders.view",
        "orders.update_status",
        "orders.add_note",
        "customers.view",
        "checkout.view",
        "shipping.view",
        "settings.view",
    },
    "catalog": {
        "dashboard.view",
        "catalog.view",
        "catalog.product.view",
        "catalog.product.create",
        "catalog.product.update",
        "catalog.product.delete",
        "catalog.inventory.update",
        "catalog.category.manage",
        "catalog.product_customization.update",
        "customization.view",
        "customization.sessions.view",
        "customization.models.assign",
        "layout.view",
        "layout.preview",
        "settings.view",
    },
    "marketing": {
        "dashboard.view",
        "catalog.view",
        "catalog.product.view",
        "customization.view",
        "layout.view",
        "layout.preview",
        "layout.update",
        "layout.assets.update",
        "discounts.view",
        "discounts.create",
        "discounts.update",
        "discounts.delete",
        "reports.view",
        "settings.view",
    },
}


def role_permissions(role_key: str) -> set[str]:
    """Return the set of permission keys granted to a role.

    Args:
        role_key: The role key (e.g. ``owner``).

    Returns:
        The granted permission keys, or an empty set for an unknown role.
    """
    return ROLE_PERMISSIONS.get(role_key, set())
