/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeamRouteImport } from './routes/_layout/team'
import { Route as LayoutStoreSettingsRouteImport } from './routes/_layout/store-settings'
import { Route as LayoutStoreLayoutRouteImport } from './routes/_layout/store-layout'
import { Route as LayoutStoreContentRouteImport } from './routes/_layout/store-content'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamRoute = LayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreSettingsRoute = LayoutStoreSettingsRouteImport.update({
  id: '/store-settings',
  path: '/store-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreLayoutRoute = LayoutStoreLayoutRouteImport.update({
  id: '/store-layout',
  path: '/store-layout',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoreContentRoute = LayoutStoreContentRouteImport.update({
  id: '/store-content',
  path: '/store-content',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/orders': typeof LayoutOrdersRoute
  '/products': typeof LayoutProductsRoute
  '/settings': typeof LayoutSettingsRoute
  '/store-content': typeof LayoutStoreContentRoute
  '/store-layout': typeof LayoutStoreLayoutRoute
  '/store-settings': typeof LayoutStoreSettingsRoute
  '/team': typeof LayoutTeamRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/orders': typeof LayoutOrdersRoute
  '/products': typeof LayoutProductsRoute
  '/settings': typeof LayoutSettingsRoute
  '/store-content': typeof LayoutStoreContentRoute
  '/store-layout': typeof LayoutStoreLayoutRoute
  '/store-settings': typeof LayoutStoreSettingsRoute
  '/team': typeof LayoutTeamRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/store-content': typeof LayoutStoreContentRoute
  '/_layout/store-layout': typeof LayoutStoreLayoutRoute
  '/_layout/store-settings': typeof LayoutStoreSettingsRoute
  '/_layout/team': typeof LayoutTeamRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/orders'
    | '/products'
    | '/settings'
    | '/store-content'
    | '/store-layout'
    | '/store-settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/orders'
    | '/products'
    | '/settings'
    | '/store-content'
    | '/store-layout'
    | '/store-settings'
    | '/team'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/orders'
    | '/_layout/products'
    | '/_layout/settings'
    | '/_layout/store-content'
    | '/_layout/store-layout'
    | '/_layout/store-settings'
    | '/_layout/team'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team': {
      id: '/_layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store-settings': {
      id: '/_layout/store-settings'
      path: '/store-settings'
      fullPath: '/store-settings'
      preLoaderRoute: typeof LayoutStoreSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store-layout': {
      id: '/_layout/store-layout'
      path: '/store-layout'
      fullPath: '/store-layout'
      preLoaderRoute: typeof LayoutStoreLayoutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/store-content': {
      id: '/_layout/store-content'
      path: '/store-content'
      fullPath: '/store-content'
      preLoaderRoute: typeof LayoutStoreContentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStoreContentRoute: typeof LayoutStoreContentRoute
  LayoutStoreLayoutRoute: typeof LayoutStoreLayoutRoute
  LayoutStoreSettingsRoute: typeof LayoutStoreSettingsRoute
  LayoutTeamRoute: typeof LayoutTeamRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStoreContentRoute: LayoutStoreContentRoute,
  LayoutStoreLayoutRoute: LayoutStoreLayoutRoute,
  LayoutStoreSettingsRoute: LayoutStoreSettingsRoute,
  LayoutTeamRoute: LayoutTeamRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
