"""create store members and roles

Revision ID: 067477c95fc2
Revises: c2d3e4f5a6b7
Create Date: 2026-06-03 22:18:29.574203

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '067477c95fc2'
down_revision = 'c2d3e4f5a6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_roles_key'), 'store_roles', ['key'], unique=True)
    op.create_table('store_members',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'removed', name='membershipstatus'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['store_roles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_members_role_id'), 'store_members', ['role_id'], unique=False)
    op.create_index(op.f('ix_store_members_store_id'), 'store_members', ['store_id'], unique=False)
    op.create_index('ix_store_members_store_status', 'store_members', ['store_id', 'status'], unique=False)
    op.create_index('ix_store_members_store_user_active', 'store_members', ['store_id', 'user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_store_members_user_id'), 'store_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_members_user_id'), table_name='store_members')
    op.drop_index('ix_store_members_store_user_active', table_name='store_members', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_store_members_store_status', table_name='store_members')
    op.drop_index(op.f('ix_store_members_store_id'), table_name='store_members')
    op.drop_index(op.f('ix_store_members_role_id'), table_name='store_members')
    op.drop_table('store_members')
    op.drop_index(op.f('ix_store_roles_key'), table_name='store_roles')
    op.drop_table('store_roles')
    sa.Enum(name='membershipstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
