"""add settings_schema to content_theme_templates

Revision ID: 18847c0960d7
Revises: 9486ba430691
Create Date: 2026-06-10 16:42:59.561261

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '18847c0960d7'
down_revision = '9486ba430691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_theme_templates', sa.Column('settings_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_theme_templates', 'settings_schema')
    # ### end Alembic commands ###
