"""customization_cart_and_order_items

Revision ID: 1f99190368ad
Revises: c5405babf7da
Create Date: 2026-06-14 08:06:09.967285

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1f99190368ad'
down_revision = 'c5405babf7da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_cart_items',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cart_item_id', sa.Uuid(), nullable=False),
    sa.Column('customization_session_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ),
    sa.ForeignKeyConstraint(['customization_session_id'], ['customization_sessions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customization_cart_items_cart_item_id'), 'customization_cart_items', ['cart_item_id'], unique=False)
    op.create_index(op.f('ix_customization_cart_items_customization_session_id'), 'customization_cart_items', ['customization_session_id'], unique=False)
    op.create_index('ix_customization_cart_items_store_cart_item', 'customization_cart_items', ['store_id', 'cart_item_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_customization_cart_items_store_id'), 'customization_cart_items', ['store_id'], unique=False)
    op.create_table('customization_order_items',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('customization_session_id', sa.Uuid(), nullable=False),
    sa.Column('platform_3d_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('snapshot_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['customization_session_id'], ['customization_sessions.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_orders.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.ForeignKeyConstraint(['platform_3d_model_version_id'], ['platform_3d_model_versions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customization_order_items_customization_session_id'), 'customization_order_items', ['customization_session_id'], unique=False)
    op.create_index(op.f('ix_customization_order_items_order_id'), 'customization_order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_customization_order_items_order_item_id'), 'customization_order_items', ['order_item_id'], unique=False)
    op.create_index(op.f('ix_customization_order_items_platform_3d_model_version_id'), 'customization_order_items', ['platform_3d_model_version_id'], unique=False)
    op.create_index(op.f('ix_customization_order_items_store_id'), 'customization_order_items', ['store_id'], unique=False)
    op.create_index('ix_customization_order_items_store_order', 'customization_order_items', ['store_id', 'order_id'], unique=False)
    op.create_index('ix_customization_order_items_store_order_item', 'customization_order_items', ['store_id', 'order_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customization_order_items_store_order_item', table_name='customization_order_items')
    op.drop_index('ix_customization_order_items_store_order', table_name='customization_order_items')
    op.drop_index(op.f('ix_customization_order_items_store_id'), table_name='customization_order_items')
    op.drop_index(op.f('ix_customization_order_items_platform_3d_model_version_id'), table_name='customization_order_items')
    op.drop_index(op.f('ix_customization_order_items_order_item_id'), table_name='customization_order_items')
    op.drop_index(op.f('ix_customization_order_items_order_id'), table_name='customization_order_items')
    op.drop_index(op.f('ix_customization_order_items_customization_session_id'), table_name='customization_order_items')
    op.drop_table('customization_order_items')
    op.drop_index(op.f('ix_customization_cart_items_store_id'), table_name='customization_cart_items')
    op.drop_index('ix_customization_cart_items_store_cart_item', table_name='customization_cart_items', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_customization_cart_items_customization_session_id'), table_name='customization_cart_items')
    op.drop_index(op.f('ix_customization_cart_items_cart_item_id'), table_name='customization_cart_items')
    op.drop_table('customization_cart_items')
    # ### end Alembic commands ###
