"""create media_files and link catalog images

Revision ID: 2262615e4dd0
Revises: db3416735b1e
Create Date: 2026-06-08 10:39:30.174233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2262615e4dd0'
down_revision = 'db3416735b1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=True),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'ready', 'failed', name='mediastatus'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_media_files_owner_id'), 'media_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_files_owner_type'), 'media_files', ['owner_type'], unique=False)
    op.create_index(op.f('ix_media_files_store_id'), 'media_files', ['store_id'], unique=False)
    op.create_index('ix_media_files_store_id_id', 'media_files', ['store_id', 'id'], unique=False)
    op.create_index('ix_media_files_store_owner', 'media_files', ['store_id', 'owner_type', 'owner_id'], unique=False)
    op.create_foreign_key('fk_catalog_product_images_media_file_id', 'catalog_product_images', 'media_files', ['media_file_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_catalog_product_images_media_file_id', 'catalog_product_images', type_='foreignkey')
    op.drop_index('ix_media_files_store_owner', table_name='media_files')
    op.drop_index('ix_media_files_store_id_id', table_name='media_files')
    op.drop_index(op.f('ix_media_files_store_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_owner_type'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_owner_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
