"""shipping methods

Revision ID: 50108c983547
Revises: 6eeee8b19085
Create Date: 2026-06-11 22:25:59.683072

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '50108c983547'
down_revision = '6eeee8b19085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_methods',
    sa.Column('type', sa.Enum('fixed_shipping', 'free_shipping', 'local_pickup', 'private_delivery', name='shippingmethodtype'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('price_amount_minor', sa.Integer(), nullable=True),
    sa.Column('min_order_amount_minor', sa.Integer(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_methods_store_id'), 'shipping_methods', ['store_id'], unique=False)
    op.create_index('ix_shipping_methods_store_type_active', 'shipping_methods', ['store_id', 'type', 'is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    op.drop_index('ix_shipping_methods_store_type_active', table_name='shipping_methods')
    op.drop_index(op.f('ix_shipping_methods_store_id'), table_name='shipping_methods')
    op.drop_table('shipping_methods')
    sa.Enum(name='shippingmethodtype').drop(op.get_bind(), checkfirst=True)
