"""create store tables

Revision ID: 516224031edd
Revises: a7b8c9d0e1f2
Create Date: 2026-06-03 17:29:37.694271

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '516224031edd'
down_revision = 'a7b8c9d0e1f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_stores',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'suspended', 'blocked', 'archived', name='storestatus'), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(length=35), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_store_stores_slug_active', 'store_stores', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('store_settings',
    sa.Column('public_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('contact_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('whatsapp_number', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_settings_store_id'), 'store_settings', ['store_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_store_settings_store_id'), table_name='store_settings')
    op.drop_table('store_settings')
    op.drop_index('ix_store_stores_slug_active', table_name='store_stores', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('store_stores')
    sa.Enum(name='storestatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
