"""create content tables

Revision ID: 532902c21b7e
Revises: d5e62eb7884a
Create Date: 2026-06-08 23:49:09.609785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '532902c21b7e'
down_revision = 'd5e62eb7884a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_theme_templates',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('preview_image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_banners',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('link_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_banners_store_id'), 'content_banners', ['store_id'], unique=False)
    op.create_index('ix_content_banners_store_position', 'content_banners', ['store_id', 'position'], unique=False)
    op.create_table('content_menus',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('location', sa.Enum('header', 'footer', name='menulocation'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_menus_store_id'), 'content_menus', ['store_id'], unique=False)
    op.create_index('ix_content_menus_store_location', 'content_menus', ['store_id', 'location'], unique=False)
    op.create_table('content_pages',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_pages_store_id'), 'content_pages', ['store_id'], unique=False)
    op.create_index('ix_content_pages_store_slug_active', 'content_pages', ['store_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('content_menu_items',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('menu_id', sa.Uuid(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['content_menus.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_menu_items_menu_id'), 'content_menu_items', ['menu_id'], unique=False)
    op.create_index(op.f('ix_content_menu_items_store_id'), 'content_menu_items', ['store_id'], unique=False)
    op.create_index('ix_content_menu_items_store_menu_position', 'content_menu_items', ['store_id', 'menu_id', 'position'], unique=False)
    op.create_table('content_store_theme_settings',
    sa.Column('active_template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('banner_image_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('featured_collection_id', sa.Uuid(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('background_color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('font_family', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['active_template_id'], ['content_theme_templates.id'], ),
    sa.ForeignKeyConstraint(['featured_collection_id'], ['catalog_collections.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_store_theme_settings_active_template_id'), 'content_store_theme_settings', ['active_template_id'], unique=False)
    op.create_index(op.f('ix_content_store_theme_settings_featured_collection_id'), 'content_store_theme_settings', ['featured_collection_id'], unique=False)
    op.create_index(op.f('ix_content_store_theme_settings_store_id'), 'content_store_theme_settings', ['store_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_store_theme_settings_store_id'), table_name='content_store_theme_settings')
    op.drop_index(op.f('ix_content_store_theme_settings_featured_collection_id'), table_name='content_store_theme_settings')
    op.drop_index(op.f('ix_content_store_theme_settings_active_template_id'), table_name='content_store_theme_settings')
    op.drop_table('content_store_theme_settings')
    op.drop_index('ix_content_menu_items_store_menu_position', table_name='content_menu_items')
    op.drop_index(op.f('ix_content_menu_items_store_id'), table_name='content_menu_items')
    op.drop_index(op.f('ix_content_menu_items_menu_id'), table_name='content_menu_items')
    op.drop_table('content_menu_items')
    op.drop_index('ix_content_pages_store_slug_active', table_name='content_pages', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_content_pages_store_id'), table_name='content_pages')
    op.drop_table('content_pages')
    op.drop_index('ix_content_menus_store_location', table_name='content_menus')
    op.drop_index(op.f('ix_content_menus_store_id'), table_name='content_menus')
    op.drop_table('content_menus')
    op.drop_index('ix_content_banners_store_position', table_name='content_banners')
    op.drop_index(op.f('ix_content_banners_store_id'), table_name='content_banners')
    op.drop_table('content_banners')
    op.drop_table('content_theme_templates')
    # ### end Alembic commands ###
