"""add store country

Revision ID: 5a9d5d61b771
Revises: 532902c21b7e
Create Date: 2026-06-09 19:11:08.997336

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a9d5d61b771'
down_revision = '532902c21b7e'
branch_labels = None
depends_on = None


def upgrade():
    # Add NOT NULL with a server_default to backfill existing rows to "BR",
    # then drop the default so the app (create_store) supplies the value.
    op.add_column(
        'store_stores',
        sa.Column(
            'country',
            sqlmodel.sql.sqltypes.AutoString(length=2),
            nullable=False,
            server_default='BR',
        ),
    )
    op.alter_column('store_stores', 'country', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_stores', 'country')
    # ### end Alembic commands ###
