"""cart carts and items

Revision ID: 5d0fd62fc87b
Revises: 50108c983547
Create Date: 2026-06-11 22:42:33.487958

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5d0fd62fc87b'
down_revision = '50108c983547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_carts',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guest_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'converted', name='cartstatus'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_carts_customer_id'), 'cart_carts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cart_carts_guest_session_id'), 'cart_carts', ['guest_session_id'], unique=False)
    op.create_index('ix_cart_carts_store_customer_status', 'cart_carts', ['store_id', 'customer_id', 'status'], unique=False)
    op.create_index('ix_cart_carts_store_guest_status', 'cart_carts', ['store_id', 'guest_session_id', 'status'], unique=False)
    op.create_index(op.f('ix_cart_carts_store_id'), 'cart_carts', ['store_id'], unique=False)
    op.create_table('cart_items',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_amount_minor', sa.Integer(), nullable=False),
    sa.Column('unit_price_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['catalog_product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.create_index('ix_cart_items_store_cart', 'cart_items', ['store_id', 'cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_store_id'), 'cart_items', ['store_id'], unique=False)
    op.create_index(op.f('ix_cart_items_variant_id'), 'cart_items', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_items_variant_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_store_id'), table_name='cart_items')
    op.drop_index('ix_cart_items_store_cart', table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_table('cart_items')
    op.drop_index(op.f('ix_cart_carts_store_id'), table_name='cart_carts')
    op.drop_index('ix_cart_carts_store_guest_status', table_name='cart_carts')
    op.drop_index('ix_cart_carts_store_customer_status', table_name='cart_carts')
    op.drop_index(op.f('ix_cart_carts_guest_session_id'), table_name='cart_carts')
    op.drop_index(op.f('ix_cart_carts_customer_id'), table_name='cart_carts')
    op.drop_table('cart_carts')
    sa.Enum(name='cartstatus').drop(op.get_bind(), checkfirst=True)
