"""customers identity and guest sessions

Revision ID: 6eeee8b19085
Revises: 6d906257c2c5
Create Date: 2026-06-11 21:59:23.066128

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6eeee8b19085'
down_revision = '6d906257c2c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_profiles',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=True),
    sa.Column('phone_e164', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_profiles_store_email', 'customer_profiles', ['store_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.create_index(op.f('ix_customer_profiles_store_id'), 'customer_profiles', ['store_id'], unique=False)
    op.create_index('ix_customer_profiles_store_phone', 'customer_profiles', ['store_id', 'phone_e164'], unique=True, postgresql_where=sa.text('phone_e164 IS NOT NULL AND deleted_at IS NULL'))
    op.create_table('customer_addresses',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('line1', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('line2', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_index('ix_customer_addresses_store_customer', 'customer_addresses', ['store_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_customer_addresses_store_id'), 'customer_addresses', ['store_id'], unique=False)
    op.create_table('customer_guest_sessions',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('guest_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_guest_sessions_customer_id'), 'customer_guest_sessions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_guest_sessions_guest_session_id'), 'customer_guest_sessions', ['guest_session_id'], unique=True)
    op.create_index('ix_customer_guest_sessions_store_expires', 'customer_guest_sessions', ['store_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_customer_guest_sessions_store_id'), 'customer_guest_sessions', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_guest_sessions_store_id'), table_name='customer_guest_sessions')
    op.drop_index('ix_customer_guest_sessions_store_expires', table_name='customer_guest_sessions')
    op.drop_index(op.f('ix_customer_guest_sessions_guest_session_id'), table_name='customer_guest_sessions')
    op.drop_index(op.f('ix_customer_guest_sessions_customer_id'), table_name='customer_guest_sessions')
    op.drop_table('customer_guest_sessions')
    op.drop_index(op.f('ix_customer_addresses_store_id'), table_name='customer_addresses')
    op.drop_index('ix_customer_addresses_store_customer', table_name='customer_addresses')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index('ix_customer_profiles_store_phone', table_name='customer_profiles', postgresql_where=sa.text('phone_e164 IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_customer_profiles_store_id'), table_name='customer_profiles')
    op.drop_index('ix_customer_profiles_store_email', table_name='customer_profiles', postgresql_where=sa.text('email IS NOT NULL AND deleted_at IS NULL'))
    op.drop_table('customer_profiles')
    # ### end Alembic commands ###
