"""create platform_admin_roles and audit_logs

Revision ID: 727624122b41
Revises: 5a9d5d61b771
Create Date: 2026-06-10 15:07:47.716056

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '727624122b41'
down_revision = '5a9d5d61b771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_store_created', 'audit_logs', ['store_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_created', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('platform_admin_roles',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_platform_admin_role_user_role')
    )
    op.create_index(op.f('ix_platform_admin_roles_role'), 'platform_admin_roles', ['role'], unique=False)
    op.create_index(op.f('ix_platform_admin_roles_user_id'), 'platform_admin_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Data migration: existing superusers become platform owners; the
    # is_superuser flag is no longer used for authorization.
    op.execute(
        """
        INSERT INTO platform_admin_roles (id, user_id, role, created_at, updated_at)
        SELECT gen_random_uuid(), u.id, 'platform_owner', now(), now()
        FROM account_users u
        WHERE u.is_superuser = true
          AND NOT EXISTS (
              SELECT 1 FROM platform_admin_roles r
              WHERE r.user_id = u.id AND r.role = 'platform_owner'
          )
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_admin_roles_user_id'), table_name='platform_admin_roles')
    op.drop_index(op.f('ix_platform_admin_roles_role'), table_name='platform_admin_roles')
    op.drop_table('platform_admin_roles')
    op.drop_index('ix_audit_logs_user_created', table_name='audit_logs')
    op.drop_index('ix_audit_logs_store_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
