"""create store permissions

Revision ID: 8d0ba011eeec
Revises: 067477c95fc2
Create Date: 2026-06-03 22:36:33.132247

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8d0ba011eeec'
down_revision = '067477c95fc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_permissions_key'), 'store_permissions', ['key'], unique=True)
    op.create_index(op.f('ix_store_permissions_module'), 'store_permissions', ['module'], unique=False)
    op.create_table('store_role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['store_permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['store_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_role_permissions_permission_id'), 'store_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_store_role_permissions_role_id'), 'store_role_permissions', ['role_id'], unique=False)
    op.create_index('ix_store_role_permissions_role_perm', 'store_role_permissions', ['role_id', 'permission_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_store_role_permissions_role_perm', table_name='store_role_permissions')
    op.drop_index(op.f('ix_store_role_permissions_role_id'), table_name='store_role_permissions')
    op.drop_index(op.f('ix_store_role_permissions_permission_id'), table_name='store_role_permissions')
    op.drop_table('store_role_permissions')
    op.drop_index(op.f('ix_store_permissions_module'), table_name='store_permissions')
    op.drop_index(op.f('ix_store_permissions_key'), table_name='store_permissions')
    op.drop_table('store_permissions')
    # ### end Alembic commands ###
