"""checkout sessions and store policies

Revision ID: 9e95a44969bd
Revises: 33517f4ccbc8
Create Date: 2026-06-11 23:41:34.442978

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9e95a44969bd'
down_revision = '33517f4ccbc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout_sessions',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', name='checkoutstatus'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart_carts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkout_sessions_cart_id'), 'checkout_sessions', ['cart_id'], unique=False)
    op.create_index('ix_checkout_sessions_expires_status', 'checkout_sessions', ['expires_at', 'status'], unique=False)
    op.create_index('ix_checkout_sessions_store_cart_status', 'checkout_sessions', ['store_id', 'cart_id', 'status'], unique=False)
    op.create_index(op.f('ix_checkout_sessions_store_id'), 'checkout_sessions', ['store_id'], unique=False)
    op.add_column('store_settings', sa.Column('return_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_settings', sa.Column('exchange_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('store_settings', sa.Column('privacy_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'privacy_policy')
    op.drop_column('store_settings', 'exchange_policy')
    op.drop_column('store_settings', 'return_policy')
    op.drop_index(op.f('ix_checkout_sessions_store_id'), table_name='checkout_sessions')
    op.drop_index('ix_checkout_sessions_store_cart_status', table_name='checkout_sessions')
    op.drop_index('ix_checkout_sessions_expires_status', table_name='checkout_sessions')
    op.drop_index(op.f('ix_checkout_sessions_cart_id'), table_name='checkout_sessions')
    op.drop_table('checkout_sessions')
    sa.Enum(name='checkoutstatus').drop(op.get_bind(), checkfirst=True)
