"""create domain hosts

Revision ID: c505b47136b7
Revises: 8d0ba011eeec
Create Date: 2026-06-03 22:48:03.505064

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c505b47136b7'
down_revision = '8d0ba011eeec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_hosts',
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('platform_subdomain', 'custom_domain', name='domaintype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'failed', 'blocked', name='domainstatus'), nullable=False),
    sa.Column('ssl_status', sa.Enum('pending', 'issued', 'failed', name='sslstatus'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_hosts_host_active', 'domain_hosts', ['host'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_domain_hosts_store_id'), 'domain_hosts', ['store_id'], unique=False)
    op.create_index('ix_domain_hosts_store_status', 'domain_hosts', ['store_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_domain_hosts_store_status', table_name='domain_hosts')
    op.drop_index(op.f('ix_domain_hosts_store_id'), table_name='domain_hosts')
    op.drop_index('ix_domain_hosts_host_active', table_name='domain_hosts', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('domain_hosts')
    sa.Enum(name='domaintype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='domainstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sslstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
