"""customization_sessions_and_uploads

Revision ID: c5405babf7da
Revises: f16c7aa2b19b
Create Date: 2026-06-13 10:30:54.413592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c5405babf7da'
down_revision = 'f16c7aa2b19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_sessions',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('platform_3d_model_version_id', sa.Uuid(), nullable=False),
    sa.Column('state_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'added_to_cart', 'ordered', 'abandoned', 'expired', name='customizationsessionstatus'), nullable=False),
    sa.Column('guest_session_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('snapshot_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('public_token', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['platform_3d_model_version_id'], ['platform_3d_model_versions.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customization_sessions_expires_status', 'customization_sessions', ['expires_at', 'status'], unique=False)
    op.create_index(op.f('ix_customization_sessions_platform_3d_model_version_id'), 'customization_sessions', ['platform_3d_model_version_id'], unique=False)
    op.create_index(op.f('ix_customization_sessions_product_id'), 'customization_sessions', ['product_id'], unique=False)
    op.create_index('ix_customization_sessions_public_token', 'customization_sessions', ['public_token'], unique=True, postgresql_where=sa.text('public_token IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('ix_customization_sessions_store_customer_status', 'customization_sessions', ['store_id', 'customer_id', 'status'], unique=False)
    op.create_index('ix_customization_sessions_store_guest_status', 'customization_sessions', ['store_id', 'guest_session_id', 'status'], unique=False)
    op.create_index(op.f('ix_customization_sessions_store_id'), 'customization_sessions', ['store_id'], unique=False)
    op.create_index('ix_customization_sessions_store_product_status', 'customization_sessions', ['store_id', 'product_id', 'status'], unique=False)
    op.create_table('customization_uploads',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customization_session_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customization_session_id'], ['customization_sessions.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customization_uploads_customization_session_id'), 'customization_uploads', ['customization_session_id'], unique=False)
    op.create_index(op.f('ix_customization_uploads_store_id'), 'customization_uploads', ['store_id'], unique=False)
    op.create_index('ix_customization_uploads_store_session', 'customization_uploads', ['store_id', 'customization_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customization_uploads_store_session', table_name='customization_uploads')
    op.drop_index(op.f('ix_customization_uploads_store_id'), table_name='customization_uploads')
    op.drop_index(op.f('ix_customization_uploads_customization_session_id'), table_name='customization_uploads')
    op.drop_table('customization_uploads')
    op.drop_index('ix_customization_sessions_store_product_status', table_name='customization_sessions')
    op.drop_index(op.f('ix_customization_sessions_store_id'), table_name='customization_sessions')
    op.drop_index('ix_customization_sessions_store_guest_status', table_name='customization_sessions')
    op.drop_index('ix_customization_sessions_store_customer_status', table_name='customization_sessions')
    op.drop_index('ix_customization_sessions_public_token', table_name='customization_sessions', postgresql_where=sa.text('public_token IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_customization_sessions_product_id'), table_name='customization_sessions')
    op.drop_index(op.f('ix_customization_sessions_platform_3d_model_version_id'), table_name='customization_sessions')
    op.drop_index('ix_customization_sessions_expires_status', table_name='customization_sessions')
    op.drop_table('customization_sessions')
    # ### end Alembic commands ###
