"""platform 3d catalog

Revision ID: c7c6df86b5d9
Revises: dce02418fed9
Create Date: 2026-06-12 21:56:16.699620

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c7c6df86b5d9'
down_revision = 'dce02418fed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_3d_models',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_platform_3d_models_category', 'platform_3d_models', ['category'], unique=False)
    op.create_index('ix_platform_3d_models_slug_active', 'platform_3d_models', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('platform_3d_model_versions',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('glb_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('printable_areas', sa.JSON(), nullable=True),
    sa.Column('text_config', sa.JSON(), nullable=True),
    sa.Column('art_limits', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['platform_3d_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_3d_model_versions_model_id'), 'platform_3d_model_versions', ['model_id'], unique=False)
    op.create_index('ix_platform_3d_model_versions_model_version', 'platform_3d_model_versions', ['model_id', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_platform_3d_model_versions_model_version', table_name='platform_3d_model_versions')
    op.drop_index(op.f('ix_platform_3d_model_versions_model_id'), table_name='platform_3d_model_versions')
    op.drop_table('platform_3d_model_versions')
    op.drop_index('ix_platform_3d_models_slug_active', table_name='platform_3d_models', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_platform_3d_models_category', table_name='platform_3d_models')
    op.drop_table('platform_3d_models')
    # ### end Alembic commands ###
