"""drop store_settings is_published

Revision ID: d5e62eb7884a
Revises: 2262615e4dd0
Create Date: 2026-06-08 16:53:38.284262

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd5e62eb7884a'
down_revision = '2262615e4dd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store_settings', 'is_published')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store_settings', sa.Column('is_published', sa.BOOLEAN(), server_default=sa.false(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
