"""create catalog tables

Revision ID: db3416735b1e
Revises: c505b47136b7
Create Date: 2026-06-08 01:52:15.888728

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db3416735b1e'
down_revision = 'c505b47136b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_categories',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_categories_store_id'), 'catalog_categories', ['store_id'], unique=False)
    op.create_index('ix_catalog_categories_store_slug_active', 'catalog_categories', ['store_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('catalog_collections',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_collections_store_id'), 'catalog_collections', ['store_id'], unique=False)
    op.create_index('ix_catalog_collections_store_slug_active', 'catalog_collections', ['store_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('catalog_products',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='productstatus'), nullable=False),
    sa.Column('price_amount_minor', sa.Integer(), nullable=False),
    sa.Column('price_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_products_store_created', 'catalog_products', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_catalog_products_store_id'), 'catalog_products', ['store_id'], unique=False)
    op.create_index('ix_catalog_products_store_slug_active', 'catalog_products', ['store_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_catalog_products_store_status', 'catalog_products', ['store_id', 'status'], unique=False)
    op.create_table('catalog_product_categories',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_product_categories_category_id'), 'catalog_product_categories', ['category_id'], unique=False)
    op.create_index('ix_catalog_product_categories_pair', 'catalog_product_categories', ['product_id', 'category_id'], unique=True)
    op.create_index(op.f('ix_catalog_product_categories_product_id'), 'catalog_product_categories', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalog_product_categories_store_id'), 'catalog_product_categories', ['store_id'], unique=False)
    op.create_table('catalog_product_images',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('media_file_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_catalog_images_store_product_position', 'catalog_product_images', ['store_id', 'product_id', 'position'], unique=False)
    op.create_index(op.f('ix_catalog_product_images_media_file_id'), 'catalog_product_images', ['media_file_id'], unique=False)
    op.create_index(op.f('ix_catalog_product_images_product_id'), 'catalog_product_images', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalog_product_images_store_id'), 'catalog_product_images', ['store_id'], unique=False)
    op.create_table('catalog_product_variants',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('price_override_amount_minor', sa.Integer(), nullable=True),
    sa.Column('price_override_currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='productvariantstatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_product_variants_product_id'), 'catalog_product_variants', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalog_product_variants_store_id'), 'catalog_product_variants', ['store_id'], unique=False)
    op.create_index('ix_catalog_variants_store_product_status', 'catalog_product_variants', ['store_id', 'product_id', 'status'], unique=False)
    op.create_table('catalog_inventory_items',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['catalog_product_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_inventory_items_product_id'), 'catalog_inventory_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_catalog_inventory_items_store_id'), 'catalog_inventory_items', ['store_id'], unique=False)
    op.create_index(op.f('ix_catalog_inventory_items_variant_id'), 'catalog_inventory_items', ['variant_id'], unique=False)
    op.create_index('ix_catalog_inventory_store_product_variant', 'catalog_inventory_items', ['store_id', 'product_id', 'variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_catalog_inventory_store_product_variant', table_name='catalog_inventory_items')
    op.drop_index(op.f('ix_catalog_inventory_items_variant_id'), table_name='catalog_inventory_items')
    op.drop_index(op.f('ix_catalog_inventory_items_store_id'), table_name='catalog_inventory_items')
    op.drop_index(op.f('ix_catalog_inventory_items_product_id'), table_name='catalog_inventory_items')
    op.drop_table('catalog_inventory_items')
    op.drop_index('ix_catalog_variants_store_product_status', table_name='catalog_product_variants')
    op.drop_index(op.f('ix_catalog_product_variants_store_id'), table_name='catalog_product_variants')
    op.drop_index(op.f('ix_catalog_product_variants_product_id'), table_name='catalog_product_variants')
    op.drop_table('catalog_product_variants')
    op.drop_index(op.f('ix_catalog_product_images_store_id'), table_name='catalog_product_images')
    op.drop_index(op.f('ix_catalog_product_images_product_id'), table_name='catalog_product_images')
    op.drop_index(op.f('ix_catalog_product_images_media_file_id'), table_name='catalog_product_images')
    op.drop_index('ix_catalog_images_store_product_position', table_name='catalog_product_images')
    op.drop_table('catalog_product_images')
    op.drop_index(op.f('ix_catalog_product_categories_store_id'), table_name='catalog_product_categories')
    op.drop_index(op.f('ix_catalog_product_categories_product_id'), table_name='catalog_product_categories')
    op.drop_index('ix_catalog_product_categories_pair', table_name='catalog_product_categories')
    op.drop_index(op.f('ix_catalog_product_categories_category_id'), table_name='catalog_product_categories')
    op.drop_table('catalog_product_categories')
    op.drop_index('ix_catalog_products_store_status', table_name='catalog_products')
    op.drop_index('ix_catalog_products_store_slug_active', table_name='catalog_products', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_catalog_products_store_id'), table_name='catalog_products')
    op.drop_index('ix_catalog_products_store_created', table_name='catalog_products')
    op.drop_table('catalog_products')
    op.drop_index('ix_catalog_collections_store_slug_active', table_name='catalog_collections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_catalog_collections_store_id'), table_name='catalog_collections')
    op.drop_table('catalog_collections')
    op.drop_index('ix_catalog_categories_store_slug_active', table_name='catalog_categories', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_catalog_categories_store_id'), table_name='catalog_categories')
    op.drop_table('catalog_categories')
    # ### end Alembic commands ###
