"""coupons + cart coupon_code

Revision ID: dce02418fed9
Revises: f11beee66d67
Create Date: 2026-06-12 13:20:11.044965

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dce02418fed9'
down_revision = 'f11beee66d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_coupons',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('type', sa.Enum('percentage', 'fixed', name='coupontype'), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_subtotal_amount_minor', sa.Integer(), nullable=False),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discount_coupons_store_code', 'discount_coupons', ['store_id', 'code'], unique=True, postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.create_index(op.f('ix_discount_coupons_store_id'), 'discount_coupons', ['store_id'], unique=False)
    op.create_table('discount_coupon_redemptions',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('coupon_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['discount_coupons.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer_profiles.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_orders.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_coupon_redemptions_coupon_id'), 'discount_coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_discount_coupon_redemptions_customer_id'), 'discount_coupon_redemptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_discount_coupon_redemptions_order_id'), 'discount_coupon_redemptions', ['order_id'], unique=False)
    op.create_index(op.f('ix_discount_coupon_redemptions_store_id'), 'discount_coupon_redemptions', ['store_id'], unique=False)
    op.create_index('ix_discount_redemptions_store_coupon', 'discount_coupon_redemptions', ['store_id', 'coupon_id'], unique=False)
    op.add_column('cart_carts', sa.Column('coupon_code', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_carts', 'coupon_code')
    op.drop_index('ix_discount_redemptions_store_coupon', table_name='discount_coupon_redemptions')
    op.drop_index(op.f('ix_discount_coupon_redemptions_store_id'), table_name='discount_coupon_redemptions')
    op.drop_index(op.f('ix_discount_coupon_redemptions_order_id'), table_name='discount_coupon_redemptions')
    op.drop_index(op.f('ix_discount_coupon_redemptions_customer_id'), table_name='discount_coupon_redemptions')
    op.drop_index(op.f('ix_discount_coupon_redemptions_coupon_id'), table_name='discount_coupon_redemptions')
    op.drop_table('discount_coupon_redemptions')
    op.drop_index(op.f('ix_discount_coupons_store_id'), table_name='discount_coupons')
    op.drop_index('ix_discount_coupons_store_code', table_name='discount_coupons', postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.drop_table('discount_coupons')
    sa.Enum(name='coupontype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
