"""customization_composite_key

Revision ID: ea7cf5fe8d46
Revises: 1f99190368ad
Create Date: 2026-06-14 13:19:38.305013

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea7cf5fe8d46'
down_revision = '1f99190368ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customization_order_items', sa.Column('composite_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('customization_sessions', sa.Column('composite_key', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customization_sessions', 'composite_key')
    op.drop_column('customization_order_items', 'composite_key')
    # ### end Alembic commands ###
