"""customization_product_settings

Revision ID: f16c7aa2b19b
Revises: c7c6df86b5d9
Create Date: 2026-06-13 09:49:53.419969

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f16c7aa2b19b'
down_revision = 'c7c6df86b5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customization_product_settings',
    sa.Column('production_notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('platform_3d_model_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['platform_3d_model_id'], ['platform_3d_models.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['catalog_products.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customization_product_settings_platform_3d_model_id'), 'customization_product_settings', ['platform_3d_model_id'], unique=False)
    op.create_index(op.f('ix_customization_product_settings_product_id'), 'customization_product_settings', ['product_id'], unique=False)
    op.create_index(op.f('ix_customization_product_settings_store_id'), 'customization_product_settings', ['store_id'], unique=False)
    op.create_index('ix_customization_product_settings_store_product', 'customization_product_settings', ['store_id', 'product_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customization_product_settings_store_product', table_name='customization_product_settings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_customization_product_settings_store_id'), table_name='customization_product_settings')
    op.drop_index(op.f('ix_customization_product_settings_product_id'), table_name='customization_product_settings')
    op.drop_index(op.f('ix_customization_product_settings_platform_3d_model_id'), table_name='customization_product_settings')
    op.drop_table('customization_product_settings')
    # ### end Alembic commands ###
