"""create content_store_template_settings

Revision ID: f7fbb7746388
Revises: 18847c0960d7
Create Date: 2026-06-11 12:38:38.318196

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f7fbb7746388'
down_revision = '18847c0960d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_store_template_settings',
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('delete_reason', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['store_stores.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['content_theme_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_store_template_settings_store_id'), 'content_store_template_settings', ['store_id'], unique=False)
    op.create_index('ix_content_store_template_settings_store_template_active', 'content_store_template_settings', ['store_id', 'template_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_content_store_template_settings_template_id'), 'content_store_template_settings', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_store_template_settings_template_id'), table_name='content_store_template_settings')
    op.drop_index('ix_content_store_template_settings_store_template_active', table_name='content_store_template_settings', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_content_store_template_settings_store_id'), table_name='content_store_template_settings')
    op.drop_table('content_store_template_settings')
    # ### end Alembic commands ###
