// This file is auto-generated by @hey-api/openapi-ts

export const BillingPlanCreateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 50,
            title: 'Key',
            description: 'Stable plan identifier'
        },
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        monthly_price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Monthly Price Amount Minor',
            description: 'Monthly price in minor units'
        },
        monthly_price_currency: {
            type: 'string',
            maxLength: 3,
            title: 'Monthly Price Currency',
            description: 'ISO 4217 currency code'
        },
        commission_bps: {
            type: 'integer',
            minimum: 0,
            title: 'Commission Bps',
            description: 'Commission per sale in basis points (500 = 5%)'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['key', 'name', 'monthly_price_amount_minor', 'monthly_price_currency', 'commission_bps'],
    title: 'BillingPlanCreate',
    description: 'Payload to create a plan definition.'
} as const;

export const BillingPlanPublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 50,
            title: 'Key',
            description: 'Stable plan identifier'
        },
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        monthly_price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Monthly Price Amount Minor',
            description: 'Monthly price in minor units'
        },
        monthly_price_currency: {
            type: 'string',
            maxLength: 3,
            title: 'Monthly Price Currency',
            description: 'ISO 4217 currency code'
        },
        commission_bps: {
            type: 'integer',
            minimum: 0,
            title: 'Commission Bps',
            description: 'Commission per sale in basis points (500 = 5%)'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['key', 'name', 'monthly_price_amount_minor', 'monthly_price_currency', 'commission_bps', 'id'],
    title: 'BillingPlanPublic',
    description: 'A plan definition as returned via the API.'
} as const;

export const BillingPlanUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        monthly_price_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Monthly Price Amount Minor'
        },
        monthly_price_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Monthly Price Currency'
        },
        commission_bps: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commission Bps'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'BillingPlanUpdate',
    description: 'Patch payload for a plan definition (unset fields are ignored).'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const Body_media_upload_mediaSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        },
        owner_type: {
            type: 'string',
            title: 'Owner Type',
            default: 'product'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_media-upload_media'
} as const;

export const Body_platform_admin_upload_template_thumbnailSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_platform-admin-upload_template_thumbnail'
} as const;

export const CategoryCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CategoryCreate',
    description: 'Fields accepted when creating a category.'
} as const;

export const CategoryPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'id', 'store_id'],
    title: 'CategoryPublic',
    description: 'Public representation of a category.'
} as const;

export const CategoryUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CategoryUpdate',
    description: 'Partial update for a category.'
} as const;

export const ContentBannerCreateSchema = {
    properties: {
        image_url: {
            type: 'string',
            maxLength: 2048,
            title: 'Image Url'
        },
        link_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Link Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['image_url'],
    title: 'ContentBannerCreate',
    description: 'Payload to create a storefront banner.'
} as const;

export const ContentBannerPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        image_url: {
            type: 'string',
            title: 'Image Url'
        },
        link_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Link Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        position: {
            type: 'integer',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'image_url', 'is_active', 'position'],
    title: 'ContentBannerPublic',
    description: 'Public representation of a storefront banner.'
} as const;

export const ContentBannerUpdateSchema = {
    properties: {
        image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        link_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Link Url'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    title: 'ContentBannerUpdate',
    description: 'Partial update of a storefront banner (only set fields apply).'
} as const;

export const ContentMenuCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        location: {
            '$ref': '#/components/schemas/MenuLocation',
            default: 'header'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ContentMenuCreate',
    description: 'Payload to create a navigation menu.'
} as const;

export const ContentMenuItemCreateSchema = {
    properties: {
        label: {
            type: 'string',
            maxLength: 255,
            title: 'Label'
        },
        url: {
            type: 'string',
            maxLength: 2048,
            title: 'Url'
        },
        position: {
            type: 'integer',
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['label', 'url'],
    title: 'ContentMenuItemCreate',
    description: 'Payload to add an item to a navigation menu.'
} as const;

export const ContentMenuItemPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        menu_id: {
            type: 'string',
            format: 'uuid',
            title: 'Menu Id'
        },
        label: {
            type: 'string',
            title: 'Label'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        position: {
            type: 'integer',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'menu_id', 'label', 'url', 'position'],
    title: 'ContentMenuItemPublic',
    description: 'Public representation of a single menu item.'
} as const;

export const ContentMenuItemUpdateSchema = {
    properties: {
        label: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Label'
        },
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    title: 'ContentMenuItemUpdate',
    description: 'Partial update of a menu item (only set fields apply).'
} as const;

export const ContentMenuPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        location: {
            '$ref': '#/components/schemas/MenuLocation'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ContentMenuItemPublic'
            },
            type: 'array',
            title: 'Items',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'name', 'location'],
    title: 'ContentMenuPublic',
    description: 'Public representation of a navigation menu and its ordered items.'
} as const;

export const ContentMenuUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        location: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MenuLocation'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ContentMenuUpdate',
    description: 'Partial update of a navigation menu (only set fields apply).'
} as const;

export const ContentPageCreateSchema = {
    properties: {
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        }
    },
    type: 'object',
    required: ['slug', 'title'],
    title: 'ContentPageCreate',
    description: 'Payload to create an editorial page.'
} as const;

export const ContentPagePublicSchema = {
    properties: {
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        title: {
            type: 'string',
            maxLength: 255,
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        is_published: {
            type: 'boolean',
            title: 'Is Published',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['slug', 'title', 'id', 'store_id'],
    title: 'ContentPagePublic',
    description: 'Public representation of an editorial page.'
} as const;

export const ContentPageUpdateSchema = {
    properties: {
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        body: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Body'
        },
        is_published: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Published'
        }
    },
    type: 'object',
    title: 'ContentPageUpdate',
    description: 'Partial update of an editorial page (only set fields apply).'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageAttachSchema = {
    properties: {
        media_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media File Id'
        },
        position: {
            type: 'integer',
            minimum: 0,
            title: 'Position',
            default: 0
        }
    },
    type: 'object',
    required: ['media_file_id'],
    title: 'ImageAttach',
    description: 'Link a (processed) media file to a product at a position.'
} as const;

export const ImagePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        media_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Media File Id'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        variants: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variants'
        },
        status: {
            '$ref': '#/components/schemas/MediaStatus'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'product_id', 'media_file_id', 'position', 'url', 'variants', 'status'],
    title: 'ImagePublic',
    description: "Public representation of a product image (with its media's URL/status)."
} as const;

export const InventoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        variant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variant Id'
        },
        quantity: {
            type: 'integer',
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'product_id', 'variant_id', 'quantity'],
    title: 'InventoryPublic',
    description: 'Public representation of a stock entry.'
} as const;

export const InventorySetSchema = {
    properties: {
        variant_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variant Id'
        },
        quantity: {
            type: 'integer',
            minimum: 0,
            title: 'Quantity'
        }
    },
    type: 'object',
    required: ['quantity'],
    title: 'InventorySet',
    description: 'Set the stock quantity for a product (optionally a specific variant).'
} as const;

export const MediaPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        owner_type: {
            type: 'string',
            title: 'Owner Type'
        },
        owner_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Id'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        variants: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Variants'
        },
        content_type: {
            type: 'string',
            title: 'Content Type'
        },
        size: {
            type: 'integer',
            title: 'Size'
        },
        status: {
            '$ref': '#/components/schemas/MediaStatus'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'owner_type', 'owner_id', 'key', 'url', 'variants', 'content_type', 'size', 'status'],
    title: 'MediaPublic',
    description: 'Public representation of an uploaded media file.'
} as const;

export const MediaStatusSchema = {
    type: 'string',
    enum: ['processing', 'ready', 'failed'],
    title: 'MediaStatus',
    description: 'Processing status of an uploaded media file.'
} as const;

export const MembershipStatusSchema = {
    type: 'string',
    enum: ['invited', 'active', 'removed'],
    title: 'MembershipStatus',
    description: 'Lifecycle status of a store membership.'
} as const;

export const MenuLocationSchema = {
    type: 'string',
    enum: ['header', 'footer'],
    title: 'MenuLocation',
    description: `Where a store navigation menu renders on the storefront (doc 10).

Read by the storefront API (\`\`P3-SF-01\`\`) to select the header/footer menu.`
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const MyMembershipSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        },
        permissions: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Permissions'
        }
    },
    type: 'object',
    required: ['role', 'permissions'],
    title: 'MyMembership',
    description: "The current user's role and permissions in the active store."
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Password-reset payload (token + new password).'
} as const;

export const Page_BillingPlanPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BillingPlanPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[BillingPlanPublic]'
} as const;

export const Page_CategoryPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[CategoryPublic]'
} as const;

export const Page_ProductPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[ProductPublic]'
} as const;

export const Page_StoreAdminListItem_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StoreAdminListItem'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[StoreAdminListItem]'
} as const;

export const Page_StoreMemberPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StoreMemberPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[StoreMemberPublic]'
} as const;

export const Page_StorePublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StorePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[StorePublic]'
} as const;

export const Page_StorefrontProduct_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/StorefrontProduct'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[StorefrontProduct]'
} as const;

export const Page_UserPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[UserPublic]'
} as const;

export const Page_VariantPublic_Schema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/VariantPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'Page[VariantPublic]'
} as const;

export const PlatformMeSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        is_platform_admin: {
            type: 'boolean',
            title: 'Is Platform Admin'
        },
        platform_roles: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Platform Roles',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'email', 'is_platform_admin'],
    title: 'PlatformMe',
    description: 'The signed-in user and their platform roles (empty if not an admin).'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate',
    description: 'Request body for creating a user through the private endpoint.'
} as const;

export const ProductCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Price Amount Minor'
        },
        price_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Currency'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        category_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            minItems: 1,
            title: 'Category Ids'
        }
    },
    type: 'object',
    required: ['name', 'price_amount_minor', 'category_ids'],
    title: 'ProductCreate',
    description: 'Fields accepted when creating a product (status starts as ``draft``).'
} as const;

export const ProductPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/ProductStatus',
            default: 'draft'
        },
        price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Price Amount Minor',
            description: 'Price in minor units (INV-D4)'
        },
        price_currency: {
            type: 'string',
            maxLength: 3,
            title: 'Price Currency',
            description: 'ISO 4217 currency code'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'price_amount_minor', 'price_currency', 'id', 'store_id'],
    title: 'ProductPublic',
    description: 'Public representation of a product.'
} as const;

export const ProductStatusSchema = {
    type: 'string',
    enum: ['draft', 'published', 'archived'],
    title: 'ProductStatus',
    description: `Lifecycle status of a catalog product (doc 09).

- \`\`draft\`\`: never published; editable; the slug follows the name.
- \`\`published\`\`: live on the storefront; the slug is fixed.
- \`\`archived\`\`: taken offline but kept — reversible via publish; the slug
  stays reserved.

Deleting a product is a **soft delete** (\`\`deleted_at\`\`), not a status.`
} as const;

export const ProductUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        price_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Amount Minor'
        },
        price_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Currency'
        },
        is_featured: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Featured'
        }
    },
    type: 'object',
    title: 'ProductUpdate',
    description: 'Partial update for a product (unset fields are left unchanged).'
} as const;

export const ProductVariantStatusSchema = {
    type: 'string',
    enum: ['active', 'archived'],
    title: 'ProductVariantStatus',
    description: 'Lifecycle status of a product variant.'
} as const;

export const StoreAdminDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        status: {
            '$ref': '#/components/schemas/StoreStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        settings: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/StoreSettingsPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        members: {
            items: {
                '$ref': '#/components/schemas/StoreMemberPublic'
            },
            type: 'array',
            title: 'Members',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug', 'status', 'created_at'],
    title: 'StoreAdminDetail',
    description: `A store's admin detail: identity + settings + members.

Orders/volume/webhooks/commissions are **not** included here yet — those
modules do not exist in the codebase yet.`
} as const;

export const StoreAdminListItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        status: {
            '$ref': '#/components/schemas/StoreStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'slug', 'status', 'created_at'],
    title: 'StoreAdminListItem',
    description: 'A store as listed in the platform admin (cross-store).'
} as const;

export const StoreCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        slug: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Slug'
        },
        country: {
            type: 'string',
            maxLength: 2,
            minLength: 2,
            title: 'Country',
            description: 'ISO 3166-1 alpha-2'
        }
    },
    type: 'object',
    required: ['name', 'country'],
    title: 'StoreCreate',
    description: 'Payload to create a store. The ``country`` derives currency/locale (P3-LOC-01).'
} as const;

export const StoreMemberInviteSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            maxLength: 50,
            title: 'Role'
        }
    },
    type: 'object',
    required: ['email', 'role'],
    title: 'StoreMemberInvite',
    description: 'Payload to invite a member by email with a role.'
} as const;

export const StoreMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        status: {
            '$ref': '#/components/schemas/MembershipStatus'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'email', 'role', 'status'],
    title: 'StoreMemberPublic',
    description: 'A store member as returned via the API.'
} as const;

export const StoreMemberRoleUpdateSchema = {
    properties: {
        role: {
            type: 'string',
            maxLength: 50,
            title: 'Role'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'StoreMemberRoleUpdate',
    description: "Payload to change a member's role."
} as const;

export const StorePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        status: {
            '$ref': '#/components/schemas/StoreStatus',
            default: 'draft'
        },
        country: {
            type: 'string',
            maxLength: 2,
            title: 'Country',
            description: 'ISO 3166-1 alpha-2 country code',
            default: 'BR'
        },
        currency: {
            type: 'string',
            maxLength: 3,
            title: 'Currency',
            description: 'ISO 4217 currency code'
        },
        locale: {
            type: 'string',
            maxLength: 35,
            title: 'Locale'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'currency', 'locale', 'id'],
    title: 'StorePublic',
    description: 'Store as returned via the API.'
} as const;

export const StoreSettingsPublicSchema = {
    properties: {
        public_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        whatsapp_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Number'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        social_links: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Social Links'
        }
    },
    type: 'object',
    required: ['id', 'store_id'],
    title: 'StoreSettingsPublic',
    description: 'Store settings as returned via the API.'
} as const;

export const StoreSettingsUpdateSchema = {
    properties: {
        public_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        contact_email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Email'
        },
        contact_phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Phone'
        },
        whatsapp_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Number'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        social_links: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Social Links'
        }
    },
    type: 'object',
    title: 'StoreSettingsUpdate',
    description: 'Editable store settings (all optional).'
} as const;

export const StoreStatusSchema = {
    type: 'string',
    enum: ['draft', 'active', 'paused', 'suspended', 'blocked'],
    title: 'StoreStatus',
    description: `Lifecycle status of a store (doc 09).

- \`\`draft\`\`: created, not yet published (not served on the storefront).
- \`\`active\`\`: published/live — the only status the storefront serves.
- \`\`paused\`\`: taken offline by the merchant (reversible via publish).
- \`\`suspended\`\`/\`\`blocked\`\`: turned off by the platform admin; the
  dashboard guard blocks access.

Removing a store is a **soft delete** (\`\`deleted_at\`\`), never a status.`
} as const;

export const StoreThemeSettingsPublicSchema = {
    properties: {
        active_template_id: {
            type: 'string',
            title: 'Active Template Id'
        },
        banner_image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Banner Image Url'
        },
        headline: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headline'
        },
        featured_collection_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Featured Collection Id'
        },
        primary_color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Primary Color'
        },
        background_color: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background Color'
        },
        font_family: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Font Family'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        }
    },
    type: 'object',
    required: ['active_template_id', 'id', 'store_id'],
    title: 'StoreThemeSettingsPublic',
    description: "Public representation of a store's theme/appearance settings."
} as const;

export const StorefrontCategorySectionSchema = {
    properties: {
        category: {
            '$ref': '#/components/schemas/CategoryPublic'
        },
        products: {
            items: {
                '$ref': '#/components/schemas/StorefrontProduct'
            },
            type: 'array',
            title: 'Products'
        }
    },
    type: 'object',
    required: ['category', 'products'],
    title: 'StorefrontCategorySection',
    description: 'A category with its first products (templates with category sections).'
} as const;

export const StorefrontHomeSchema = {
    properties: {
        store: {
            '$ref': '#/components/schemas/StorefrontStore'
        },
        theme: {
            '$ref': '#/components/schemas/StorefrontTheme'
        },
        featured_products: {
            items: {
                '$ref': '#/components/schemas/StorefrontProduct'
            },
            type: 'array',
            title: 'Featured Products'
        },
        category_sections: {
            items: {
                '$ref': '#/components/schemas/StorefrontCategorySection'
            },
            type: 'array',
            title: 'Category Sections',
            default: []
        }
    },
    type: 'object',
    required: ['store', 'theme', 'featured_products'],
    title: 'StorefrontHome',
    description: 'The storefront home payload: store identity, active theme and highlights.'
} as const;

export const StorefrontProductSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        slug: {
            type: 'string',
            maxLength: 255,
            title: 'Slug'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        status: {
            '$ref': '#/components/schemas/ProductStatus',
            default: 'draft'
        },
        price_amount_minor: {
            type: 'integer',
            minimum: 0,
            title: 'Price Amount Minor',
            description: 'Price in minor units (INV-D4)'
        },
        price_currency: {
            type: 'string',
            maxLength: 3,
            title: 'Price Currency',
            description: 'ISO 4217 currency code'
        },
        is_featured: {
            type: 'boolean',
            title: 'Is Featured',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        images: {
            items: {
                '$ref': '#/components/schemas/ImagePublic'
            },
            type: 'array',
            title: 'Images',
            default: []
        }
    },
    type: 'object',
    required: ['name', 'slug', 'price_amount_minor', 'price_currency', 'id', 'store_id'],
    title: 'StorefrontProduct',
    description: 'A published product with its images, for storefront cards and detail.'
} as const;

export const StorefrontStoreSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        currency: {
            type: 'string',
            title: 'Currency'
        },
        locale: {
            type: 'string',
            title: 'Locale'
        },
        public_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Public Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        logo_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Logo Url'
        },
        whatsapp_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Whatsapp Number'
        }
    },
    type: 'object',
    required: ['name', 'slug', 'currency', 'locale'],
    title: 'StorefrontStore',
    description: 'Public store identity/contact (from ``stores``/``store_settings``).'
} as const;

export const StorefrontThemeSchema = {
    properties: {
        active_template_id: {
            type: 'string',
            title: 'Active Template Id'
        },
        banner_image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Banner Image Url'
        },
        headline: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headline'
        },
        featured_collection_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Featured Collection Id'
        },
        primary_color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Primary Color'
        },
        background_color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Background Color'
        },
        font_family: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Font Family'
        },
        settings: {
            additionalProperties: true,
            type: 'object',
            title: 'Settings',
            default: {}
        }
    },
    type: 'object',
    required: ['active_template_id'],
    title: 'StorefrontTheme',
    description: `Public appearance for rendering (active template + theme fields + chrome).

Read-only: a store with no settings yet falls back to the default template
without creating a row. \`\`settings\`\` are the active template's schema-driven
chrome values (defaults merged with the store's overrides).`
} as const;

export const TemplateSettingsPublicSchema = {
    properties: {
        template_id: {
            type: 'string',
            title: 'Template Id'
        },
        settings: {
            additionalProperties: true,
            type: 'object',
            title: 'Settings',
            default: {}
        }
    },
    type: 'object',
    required: ['template_id'],
    title: 'TemplateSettingsPublic',
    description: "A store's saved chrome overrides for a template (keyed by schema ``key``)."
} as const;

export const TemplateSettingsUpdateSchema = {
    properties: {
        settings: {
            additionalProperties: true,
            type: 'object',
            title: 'Settings'
        }
    },
    type: 'object',
    required: ['settings'],
    title: 'TemplateSettingsUpdate',
    description: "Patch the store's chrome overrides for the active template."
} as const;

export const ThemeTemplateAdminPublicSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        preview_image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preview Image Url'
        },
        settings_schema: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Settings Schema'
        }
    },
    type: 'object',
    required: ['id', 'name', 'is_active'],
    title: 'ThemeTemplateAdminPublic',
    description: 'A theme template as managed in the platform admin.'
} as const;

export const ThemeTemplateCreateSchema = {
    properties: {
        id: {
            type: 'string',
            maxLength: 50,
            title: 'Id'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        preview_image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preview Image Url'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ThemeTemplateCreate',
    description: 'Payload to register a theme template (its code must already exist).'
} as const;

export const ThemeTemplatePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        preview_image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preview Image Url'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        settings_schema: {
            anyOf: [
                {
                    items: {
                        additionalProperties: true,
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Settings Schema'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'ThemeTemplatePublic',
    description: 'Public representation of a global theme template (with its editable schema).'
} as const;

export const ThemeTemplateUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        preview_image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Preview Image Url'
        }
    },
    type: 'object',
    title: 'ThemeTemplateUpdate',
    description: 'Patch payload for a theme template (unset fields are ignored).'
} as const;

export const ThemeUpdateSchema = {
    properties: {
        active_template_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active Template Id'
        },
        banner_image_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2048
                },
                {
                    type: 'null'
                }
            ],
            title: 'Banner Image Url'
        },
        headline: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Headline'
        },
        featured_collection_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Featured Collection Id'
        }
    },
    type: 'object',
    title: 'ThemeUpdate',
    description: `Partial theme update: apply a template and/or edit appearance.

Only the fields actually sent are applied (\`\`exclude_unset\`\`). Setting
\`\`active_template_id\`\` validates the target is an available template.`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'JSON payload containing an access token.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Self password-change payload.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Payload to create an account user.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'Account user as returned via the API.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Self-registration payload.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Admin update payload (all fields optional).'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Self profile-update payload.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'Paginated list of account users.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VariantCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        attributes: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attributes'
        },
        price_override_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Amount Minor'
        },
        price_override_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Currency'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'VariantCreate',
    description: 'Fields accepted when creating a product variant.'
} as const;

export const VariantPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        store_id: {
            type: 'string',
            format: 'uuid',
            title: 'Store Id'
        },
        product_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        attributes: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attributes'
        },
        price_override_amount_minor: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Amount Minor'
        },
        price_override_currency: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Currency'
        },
        status: {
            '$ref': '#/components/schemas/ProductVariantStatus'
        }
    },
    type: 'object',
    required: ['id', 'store_id', 'product_id', 'name', 'sku', 'attributes', 'price_override_amount_minor', 'price_override_currency', 'status'],
    title: 'VariantPublic',
    description: 'Public representation of a product variant.'
} as const;

export const VariantUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        sku: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sku'
        },
        attributes: {
            anyOf: [
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Attributes'
        },
        price_override_amount_minor: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Amount Minor'
        },
        price_override_currency: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Override Currency'
        }
    },
    type: 'object',
    title: 'VariantUpdate',
    description: 'Partial update for a product variant.'
} as const;