// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_media_upload_media = {
    file: string;
    owner_type?: string;
};

/**
 * Fields accepted when creating a category.
 */
export type CategoryCreate = {
    name: string;
    slug?: (string | null);
    description?: (string | null);
};

/**
 * Public representation of a category.
 */
export type CategoryPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    id: string;
    store_id: string;
};

/**
 * Partial update for a category.
 */
export type CategoryUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
};

/**
 * Public representation of an editorial page.
 */
export type ContentPagePublic = {
    slug: string;
    title: string;
    body?: (string | null);
    is_published?: boolean;
    id: string;
    store_id: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Link a (processed) media file to a product at a position.
 */
export type ImageAttach = {
    media_file_id: string;
    position?: number;
};

/**
 * Public representation of a product image (with its media's URL/status).
 */
export type ImagePublic = {
    id: string;
    store_id: string;
    product_id: string;
    media_file_id: string;
    position: number;
    url: string;
    variants: ({
    [key: string]: (string);
} | null);
    status: MediaStatus;
};

/**
 * Public representation of a stock entry.
 */
export type InventoryPublic = {
    id: string;
    store_id: string;
    product_id: string;
    variant_id: (string | null);
    quantity: number;
};

/**
 * Set the stock quantity for a product (optionally a specific variant).
 */
export type InventorySet = {
    variant_id?: (string | null);
    quantity: number;
};

/**
 * Public representation of an uploaded media file.
 */
export type MediaPublic = {
    id: string;
    store_id: string;
    owner_type: string;
    owner_id: (string | null);
    key: string;
    url: string;
    variants: ({
    [key: string]: (string);
} | null);
    content_type: string;
    size: number;
    status: MediaStatus;
};

/**
 * Processing status of an uploaded media file.
 */
export type MediaStatus = 'processing' | 'ready' | 'failed';

/**
 * Lifecycle status of a store membership.
 */
export type MembershipStatus = 'invited' | 'active' | 'removed';

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * The current user's role and permissions in the active store.
 */
export type MyMembership = {
    role: string;
    permissions: Array<(string)>;
};

/**
 * Password-reset payload (token + new password).
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

export type Page_CategoryPublic_ = {
    data: Array<CategoryPublic>;
    count: number;
};

export type Page_ProductPublic_ = {
    data: Array<ProductPublic>;
    count: number;
};

export type Page_StorefrontProduct_ = {
    data: Array<StorefrontProduct>;
    count: number;
};

export type Page_StoreMemberPublic_ = {
    data: Array<StoreMemberPublic>;
    count: number;
};

export type Page_StorePublic_ = {
    data: Array<StorePublic>;
    count: number;
};

export type Page_VariantPublic_ = {
    data: Array<VariantPublic>;
    count: number;
};

/**
 * Request body for creating a user through the private endpoint.
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Fields accepted when creating a product (status starts as ``draft``).
 */
export type ProductCreate = {
    name: string;
    slug?: (string | null);
    description?: (string | null);
    price_amount_minor: number;
    price_currency?: (string | null);
    is_featured?: boolean;
};

/**
 * Public representation of a product.
 */
export type ProductPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    status?: ProductStatus;
    /**
     * Price in minor units (INV-D4)
     */
    price_amount_minor: number;
    /**
     * ISO 4217 currency code
     */
    price_currency: string;
    is_featured?: boolean;
    id: string;
    store_id: string;
};

/**
 * Lifecycle status of a catalog product (doc 09).
 *
 * - ``draft``: never published; editable; the slug follows the name.
 * - ``published``: live on the storefront; the slug is fixed.
 * - ``archived``: taken offline but kept — reversible via publish; the slug
 * stays reserved.
 *
 * Deleting a product is a **soft delete** (``deleted_at``), not a status.
 */
export type ProductStatus = 'draft' | 'published' | 'archived';

/**
 * Partial update for a product (unset fields are left unchanged).
 */
export type ProductUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
    price_amount_minor?: (number | null);
    price_currency?: (string | null);
    is_featured?: (boolean | null);
};

/**
 * Lifecycle status of a product variant.
 */
export type ProductVariantStatus = 'active' | 'archived';

/**
 * Payload to create a store. The ``country`` derives currency/locale (P3-LOC-01).
 */
export type StoreCreate = {
    name: string;
    slug?: (string | null);
    /**
     * ISO 3166-1 alpha-2
     */
    country: string;
};

/**
 * The storefront home payload: store identity, active theme and highlights.
 */
export type StorefrontHome = {
    store: StorefrontStore;
    theme: StorefrontTheme;
    featured_products: Array<StorefrontProduct>;
};

/**
 * A published product with its images, for storefront cards and detail.
 */
export type StorefrontProduct = {
    name: string;
    slug: string;
    description?: (string | null);
    status?: ProductStatus;
    /**
     * Price in minor units (INV-D4)
     */
    price_amount_minor: number;
    /**
     * ISO 4217 currency code
     */
    price_currency: string;
    is_featured?: boolean;
    id: string;
    store_id: string;
    images?: Array<ImagePublic>;
};

/**
 * Public store identity/contact (from ``stores``/``store_settings``).
 */
export type StorefrontStore = {
    name: string;
    slug: string;
    currency: string;
    locale: string;
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    whatsapp_number?: (string | null);
};

/**
 * Public appearance for rendering (active template + theme fields).
 *
 * Read-only: a store with no settings yet falls back to the default template
 * (``classic``) without creating a row.
 */
export type StorefrontTheme = {
    active_template_id: string;
    banner_image_url?: (string | null);
    headline?: (string | null);
    featured_collection_id?: (string | null);
    primary_color?: (string | null);
    background_color?: (string | null);
    font_family?: (string | null);
};

/**
 * Payload to invite a member by email with a role.
 */
export type StoreMemberInvite = {
    email: string;
    role: string;
};

/**
 * A store member as returned via the API.
 */
export type StoreMemberPublic = {
    id: string;
    user_id: string;
    email: string;
    role: string;
    status: MembershipStatus;
};

/**
 * Payload to change a member's role.
 */
export type StoreMemberRoleUpdate = {
    role: string;
};

/**
 * Store as returned via the API.
 */
export type StorePublic = {
    name: string;
    slug: string;
    status?: StoreStatus;
    /**
     * ISO 3166-1 alpha-2 country code
     */
    country?: string;
    /**
     * ISO 4217 currency code
     */
    currency: string;
    locale: string;
    id: string;
};

/**
 * Store settings as returned via the API.
 */
export type StoreSettingsPublic = {
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    contact_email?: (string | null);
    contact_phone?: (string | null);
    whatsapp_number?: (string | null);
    address?: (string | null);
    id: string;
    store_id: string;
    social_links?: ({
    [key: string]: (string);
} | null);
};

/**
 * Editable store settings (all optional).
 */
export type StoreSettingsUpdate = {
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    contact_email?: (string | null);
    contact_phone?: (string | null);
    whatsapp_number?: (string | null);
    address?: (string | null);
    social_links?: ({
    [key: string]: (string);
} | null);
};

/**
 * Lifecycle status of a store (doc 09).
 *
 * - ``draft``: created, not yet published (not served on the storefront).
 * - ``active``: published/live — the only status the storefront serves.
 * - ``paused``: taken offline by the merchant (reversible via publish).
 * - ``suspended``/``blocked``: turned off by the platform (Fase 7); the
 * dashboard guard blocks access.
 *
 * Removing a store is a **soft delete** (``deleted_at``), never a status.
 */
export type StoreStatus = 'draft' | 'active' | 'paused' | 'suspended' | 'blocked';

/**
 * Public representation of a store's theme/appearance settings.
 */
export type StoreThemeSettingsPublic = {
    active_template_id: string;
    banner_image_url?: (string | null);
    headline?: (string | null);
    featured_collection_id?: (string | null);
    primary_color?: (string | null);
    background_color?: (string | null);
    font_family?: (string | null);
    id: string;
    store_id: string;
};

/**
 * Public representation of a global theme template.
 */
export type ThemeTemplatePublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    preview_image_url?: (string | null);
    id: string;
};

/**
 * Partial theme update: apply a template and/or edit appearance.
 *
 * Only the fields actually sent are applied (``exclude_unset``). Setting
 * ``active_template_id`` validates the target is an available template.
 */
export type ThemeUpdate = {
    active_template_id?: (string | null);
    banner_image_url?: (string | null);
    headline?: (string | null);
    featured_collection_id?: (string | null);
};

/**
 * JSON payload containing an access token.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Self password-change payload.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Payload to create an account user.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Account user as returned via the API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * Self-registration payload.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Paginated list of account users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Admin update payload (all fields optional).
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Self profile-update payload.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Fields accepted when creating a product variant.
 */
export type VariantCreate = {
    name: string;
    sku?: (string | null);
    attributes?: ({
    [key: string]: (string);
} | null);
    price_override_amount_minor?: (number | null);
    price_override_currency?: (string | null);
};

/**
 * Public representation of a product variant.
 */
export type VariantPublic = {
    id: string;
    store_id: string;
    product_id: string;
    name: string;
    sku: (string | null);
    attributes: ({
    [key: string]: (string);
} | null);
    price_override_amount_minor: (number | null);
    price_override_currency: (string | null);
    status: ProductVariantStatus;
};

/**
 * Partial update for a product variant.
 */
export type VariantUpdate = {
    name?: (string | null);
    sku?: (string | null);
    attributes?: ({
    [key: string]: (string);
} | null);
    price_override_amount_minor?: (number | null);
    price_override_currency?: (string | null);
};

export type CatalogListProductsData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type CatalogListProductsResponse = (Page_ProductPublic_);

export type CatalogCreateProductData = {
    requestBody: ProductCreate;
    storeId: string;
};

export type CatalogCreateProductResponse = (ProductPublic);

export type CatalogGetProductData = {
    productId: string;
    storeId: string;
};

export type CatalogGetProductResponse = (ProductPublic);

export type CatalogUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
    storeId: string;
};

export type CatalogUpdateProductResponse = (ProductPublic);

export type CatalogDeleteProductData = {
    productId: string;
    storeId: string;
};

export type CatalogDeleteProductResponse = (void);

export type CatalogPublishProductData = {
    productId: string;
    storeId: string;
};

export type CatalogPublishProductResponse = (ProductPublic);

export type CatalogArchiveProductData = {
    productId: string;
    storeId: string;
};

export type CatalogArchiveProductResponse = (ProductPublic);

export type CatalogListCategoriesData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type CatalogListCategoriesResponse = (Page_CategoryPublic_);

export type CatalogCreateCategoryData = {
    requestBody: CategoryCreate;
    storeId: string;
};

export type CatalogCreateCategoryResponse = (CategoryPublic);

export type CatalogUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
    storeId: string;
};

export type CatalogUpdateCategoryResponse = (CategoryPublic);

export type CatalogDeleteCategoryData = {
    categoryId: string;
    storeId: string;
};

export type CatalogDeleteCategoryResponse = (void);

export type CatalogListVariantsData = {
    limit?: number;
    productId: string;
    skip?: number;
    storeId: string;
};

export type CatalogListVariantsResponse = (Page_VariantPublic_);

export type CatalogCreateVariantData = {
    productId: string;
    requestBody: VariantCreate;
    storeId: string;
};

export type CatalogCreateVariantResponse = (VariantPublic);

export type CatalogUpdateVariantData = {
    productId: string;
    requestBody: VariantUpdate;
    storeId: string;
    variantId: string;
};

export type CatalogUpdateVariantResponse = (VariantPublic);

export type CatalogDeleteVariantData = {
    productId: string;
    storeId: string;
    variantId: string;
};

export type CatalogDeleteVariantResponse = (void);

export type CatalogListImagesData = {
    productId: string;
    storeId: string;
};

export type CatalogListImagesResponse = (Array<ImagePublic>);

export type CatalogAttachImageData = {
    productId: string;
    requestBody: ImageAttach;
    storeId: string;
};

export type CatalogAttachImageResponse = (ImagePublic);

export type CatalogRemoveImageData = {
    imageId: string;
    productId: string;
    storeId: string;
};

export type CatalogRemoveImageResponse = (void);

export type CatalogGetInventoryData = {
    productId: string;
    storeId: string;
};

export type CatalogGetInventoryResponse = ((InventoryPublic | null));

export type CatalogSetInventoryData = {
    productId: string;
    requestBody: InventorySet;
    storeId: string;
};

export type CatalogSetInventoryResponse = (InventoryPublic);

export type ContentListTemplatesData = {
    storeId: string;
};

export type ContentListTemplatesResponse = (Array<ThemeTemplatePublic>);

export type ContentGetLayoutData = {
    storeId: string;
};

export type ContentGetLayoutResponse = (StoreThemeSettingsPublic);

export type ContentUpdateLayoutData = {
    requestBody: ThemeUpdate;
    storeId: string;
};

export type ContentUpdateLayoutResponse = (StoreThemeSettingsPublic);

export type ContentPreviewLayoutData = {
    storeId: string;
    templateId: string;
};

export type ContentPreviewLayoutResponse = (StoreThemeSettingsPublic);

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type HealthHealthRedisResponse = ({
    [key: string]: (string);
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaUploadMediaData = {
    formData: Body_media_upload_media;
    storeId: string;
};

export type MediaUploadMediaResponse = (MediaPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type StorefrontGetHomeResponse = (StorefrontHome);

export type StorefrontListCategoriesResponse = (Array<CategoryPublic>);

export type StorefrontListProductsData = {
    category?: (string | null);
    limit?: number;
    skip?: number;
};

export type StorefrontListProductsResponse = (Page_StorefrontProduct_);

export type StorefrontGetProductData = {
    slug: string;
};

export type StorefrontGetProductResponse = (StorefrontProduct);

export type StorefrontGetPageData = {
    slug: string;
};

export type StorefrontGetPageResponse = (ContentPagePublic);

export type StoresCreateStoreData = {
    requestBody: StoreCreate;
};

export type StoresCreateStoreResponse = (StorePublic);

export type StoresListMyStoresData = {
    limit?: number;
    skip?: number;
};

export type StoresListMyStoresResponse = (Page_StorePublic_);

export type StoresGetStoreData = {
    storeId: string;
};

export type StoresGetStoreResponse = (StorePublic);

export type StoresGetMyMembershipData = {
    storeId: string;
};

export type StoresGetMyMembershipResponse = (MyMembership);

export type StoresGetStoreSettingsData = {
    storeId: string;
};

export type StoresGetStoreSettingsResponse = (StoreSettingsPublic);

export type StoresUpdateStoreSettingsData = {
    requestBody: StoreSettingsUpdate;
    storeId: string;
};

export type StoresUpdateStoreSettingsResponse = (StoreSettingsPublic);

export type StoresPublishStoreData = {
    storeId: string;
};

export type StoresPublishStoreResponse = (StorePublic);

export type StoresPauseStoreData = {
    storeId: string;
};

export type StoresPauseStoreResponse = (StorePublic);

export type StoresListStoreMembersData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type StoresListStoreMembersResponse = (Page_StoreMemberPublic_);

export type StoresInviteStoreMemberData = {
    requestBody: StoreMemberInvite;
    storeId: string;
};

export type StoresInviteStoreMemberResponse = (StoreMemberPublic);

export type StoresUpdateStoreMemberRoleData = {
    requestBody: StoreMemberRoleUpdate;
    storeId: string;
    userId: string;
};

export type StoresUpdateStoreMemberRoleResponse = (StoreMemberPublic);

export type StoresRemoveStoreMemberData = {
    storeId: string;
    userId: string;
};

export type StoresRemoveStoreMemberResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);