// This file is auto-generated by @hey-api/openapi-ts

/**
 * Add a product (optionally a variant) to the cart.
 */
export type AddItemInput = {
    product_id: string;
    variant_id?: (string | null);
    quantity?: number;
};

/**
 * An address provided at checkout (appended to the customer if new).
 */
export type AddressInput = {
    recipient_name?: (string | null);
    line1: string;
    number?: (string | null);
    line2?: (string | null);
    neighborhood?: (string | null);
    city: string;
    state?: (string | null);
    postal_code?: (string | null);
    /**
     * ISO 3166-1 alpha-2
     */
    country: string;
};

/**
 * Payload to create a plan definition.
 */
export type BillingPlanCreate = {
    /**
     * Stable plan identifier
     */
    key: string;
    name: string;
    /**
     * Monthly price in minor units
     */
    monthly_price_amount_minor: number;
    /**
     * ISO 4217 currency code
     */
    monthly_price_currency: string;
    /**
     * Commission per sale in basis points (500 = 5%)
     */
    commission_bps: number;
    description?: (string | null);
    is_active?: boolean;
};

/**
 * A plan definition as returned via the API.
 */
export type BillingPlanPublic = {
    /**
     * Stable plan identifier
     */
    key: string;
    name: string;
    /**
     * Monthly price in minor units
     */
    monthly_price_amount_minor: number;
    /**
     * ISO 4217 currency code
     */
    monthly_price_currency: string;
    /**
     * Commission per sale in basis points (500 = 5%)
     */
    commission_bps: number;
    description?: (string | null);
    is_active?: boolean;
    id: string;
};

/**
 * Patch payload for a plan definition (unset fields are ignored).
 */
export type BillingPlanUpdate = {
    name?: (string | null);
    monthly_price_amount_minor?: (number | null);
    monthly_price_currency?: (string | null);
    commission_bps?: (number | null);
    description?: (string | null);
    is_active?: (boolean | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_media_upload_media = {
    file: string;
    owner_type?: string;
};

export type Body_platform_admin_upload_template_thumbnail = {
    file: string;
};

/**
 * A cart line, render-ready for the storefront.
 */
export type CartItemPublic = {
    id: string;
    product_id: string;
    variant_id: (string | null);
    name: string;
    slug: string;
    image_url: (string | null);
    quantity: number;
    unit_price_amount_minor: number;
    unit_price_currency: string;
    line_total_amount_minor: number;
};

/**
 * A cart with its items and computed subtotal.
 */
export type CartPublic = {
    id: string;
    currency: string;
    item_count: number;
    subtotal_amount_minor: number;
    items: Array<CartItemPublic>;
};

/**
 * Fields accepted when creating a category.
 */
export type CategoryCreate = {
    name: string;
    slug?: (string | null);
    description?: (string | null);
};

/**
 * Public representation of a category.
 */
export type CategoryPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    id: string;
    store_id: string;
};

/**
 * Partial update for a category.
 */
export type CategoryUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
};

/**
 * Customer contact collected at checkout (no password).
 */
export type CheckoutContact = {
    name: string;
    email?: (string | null);
    phone?: (string | null);
    region?: (string | null);
};

/**
 * The checkout submission: contact + address + chosen shipping method.
 */
export type CheckoutInput = {
    contact: CheckoutContact;
    address: AddressInput;
    shipping_method_id: string;
};

/**
 * Payload to create a storefront banner.
 */
export type ContentBannerCreate = {
    image_url: string;
    link_url?: (string | null);
    title?: (string | null);
    is_active?: boolean;
    position?: number;
};

/**
 * Public representation of a storefront banner.
 */
export type ContentBannerPublic = {
    id: string;
    store_id: string;
    image_url: string;
    link_url?: (string | null);
    title?: (string | null);
    is_active: boolean;
    position: number;
};

/**
 * Partial update of a storefront banner (only set fields apply).
 */
export type ContentBannerUpdate = {
    image_url?: (string | null);
    link_url?: (string | null);
    title?: (string | null);
    is_active?: (boolean | null);
    position?: (number | null);
};

/**
 * Payload to create a navigation menu.
 */
export type ContentMenuCreate = {
    name: string;
    location?: MenuLocation;
};

/**
 * Payload to add an item to a navigation menu.
 */
export type ContentMenuItemCreate = {
    label: string;
    url: string;
    position?: number;
};

/**
 * Public representation of a single menu item.
 */
export type ContentMenuItemPublic = {
    id: string;
    menu_id: string;
    label: string;
    url: string;
    position: number;
};

/**
 * Partial update of a menu item (only set fields apply).
 */
export type ContentMenuItemUpdate = {
    label?: (string | null);
    url?: (string | null);
    position?: (number | null);
};

/**
 * Public representation of a navigation menu and its ordered items.
 */
export type ContentMenuPublic = {
    id: string;
    store_id: string;
    name: string;
    location: MenuLocation;
    items?: Array<ContentMenuItemPublic>;
};

/**
 * Partial update of a navigation menu (only set fields apply).
 */
export type ContentMenuUpdate = {
    name?: (string | null);
    location?: (MenuLocation | null);
};

/**
 * Payload to create an editorial page.
 */
export type ContentPageCreate = {
    slug: string;
    title: string;
    body?: (string | null);
    is_published?: boolean;
};

/**
 * Public representation of an editorial page.
 */
export type ContentPagePublic = {
    slug: string;
    title: string;
    body?: (string | null);
    is_published?: boolean;
    id: string;
    store_id: string;
};

/**
 * Partial update of an editorial page (only set fields apply).
 */
export type ContentPageUpdate = {
    slug?: (string | null);
    title?: (string | null);
    body?: (string | null);
    is_published?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Link a (processed) media file to a product at a position.
 */
export type ImageAttach = {
    media_file_id: string;
    position?: number;
};

/**
 * Public representation of a product image (with its media's URL/status).
 */
export type ImagePublic = {
    id: string;
    store_id: string;
    product_id: string;
    media_file_id: string;
    position: number;
    url: string;
    variants: ({
    [key: string]: (string);
} | null);
    status: MediaStatus;
};

/**
 * Public representation of a stock entry.
 */
export type InventoryPublic = {
    id: string;
    store_id: string;
    product_id: string;
    variant_id: (string | null);
    quantity: number;
};

/**
 * Set the stock quantity for a product (optionally a specific variant).
 */
export type InventorySet = {
    variant_id?: (string | null);
    quantity: number;
};

/**
 * Public representation of an uploaded media file.
 */
export type MediaPublic = {
    id: string;
    store_id: string;
    owner_type: string;
    owner_id: (string | null);
    key: string;
    url: string;
    variants: ({
    [key: string]: (string);
} | null);
    content_type: string;
    size: number;
    status: MediaStatus;
};

/**
 * Processing status of an uploaded media file.
 */
export type MediaStatus = 'processing' | 'ready' | 'failed';

/**
 * Lifecycle status of a store membership.
 */
export type MembershipStatus = 'invited' | 'active' | 'removed';

/**
 * Where a store navigation menu renders on the storefront (doc 10).
 *
 * Read by the storefront API (``P3-SF-01``) to select the header/footer menu.
 */
export type MenuLocation = 'header' | 'footer';

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * The current user's role and permissions in the active store.
 */
export type MyMembership = {
    role: string;
    permissions: Array<(string)>;
};

/**
 * Password-reset payload (token + new password).
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * The delivery address snapshotted on an order.
 */
export type OrderAddressPublic = {
    recipient_name: (string | null);
    line1: string;
    number: (string | null);
    line2: (string | null);
    neighborhood: (string | null);
    city: string;
    state: (string | null);
    postal_code: (string | null);
    country: string;
};

/**
 * The customer behind an order (for contact + WhatsApp handoff).
 */
export type OrderCustomerPublic = {
    id: string;
    name: string;
    email: (string | null);
    phone_e164: (string | null);
};

/**
 * The full order, for the panel detail (customer, address, history, notes).
 */
export type OrderDetail = {
    id: string;
    order_number: number;
    status: OrderStatus;
    currency: string;
    subtotal_amount_minor: number;
    shipping_amount_minor: number;
    discount_amount_minor: number;
    total_amount_minor: number;
    shipping_method_type: (ShippingMethodType | null);
    shipping_method_name: (string | null);
    created_at: string;
    customer: (OrderCustomerPublic | null);
    address: (OrderAddressPublic | null);
    items: Array<OrderItemPublic>;
    status_history: Array<OrderStatusHistoryPublic>;
    notes: Array<OrderNotePublic>;
};

/**
 * A purchased line (frozen name/price).
 */
export type OrderItemPublic = {
    id: string;
    product_id: string;
    variant_id: (string | null);
    name: string;
    quantity: number;
    unit_price_amount_minor: number;
    unit_price_currency: string;
    line_total_amount_minor: number;
};

/**
 * Add an internal note to an order.
 */
export type OrderNoteCreate = {
    body: string;
};

/**
 * An internal note written on an order by the merchant.
 */
export type OrderNotePublic = {
    id: string;
    body: string;
    author_user_id: (string | null);
    created_at: string;
};

/**
 * An order with its items (checkout confirmation + panel detail).
 */
export type OrderPublic = {
    id: string;
    order_number: number;
    status: OrderStatus;
    currency: string;
    subtotal_amount_minor: number;
    shipping_amount_minor: number;
    discount_amount_minor: number;
    total_amount_minor: number;
    shipping_method_type: (ShippingMethodType | null);
    shipping_method_name: (string | null);
    items: Array<OrderItemPublic>;
};

/**
 * Operational status of an order in the no-gateway phase (doc 11).
 *
 * ``pending_payment`` → ``paid`` (marked manually) → ``processing`` →
 * ``shipped`` → ``delivered``; ``canceled`` at any allowed point (restocks).
 * The payment statuses (``payment_failed``/``refunded``/``chargeback``) arrive
 * with the gateway in Fase 8 — none is created here.
 */
export type OrderStatus = 'pending_payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'canceled';

/**
 * One status transition in an order's history.
 */
export type OrderStatusHistoryPublic = {
    status: OrderStatus;
    note: (string | null);
    created_at: string;
};

/**
 * Move an order to the next operational status.
 */
export type OrderStatusUpdate = {
    status: OrderStatus;
};

/**
 * A row in the panel orders list (number + status + total + customer).
 */
export type OrderSummary = {
    id: string;
    order_number: number;
    status: OrderStatus;
    currency: string;
    total_amount_minor: number;
    item_count: number;
    customer_name: (string | null);
    created_at: string;
};

export type Page_BillingPlanPublic_ = {
    data: Array<BillingPlanPublic>;
    count: number;
};

export type Page_CategoryPublic_ = {
    data: Array<CategoryPublic>;
    count: number;
};

export type Page_OrderSummary_ = {
    data: Array<OrderSummary>;
    count: number;
};

export type Page_ProductPublic_ = {
    data: Array<ProductPublic>;
    count: number;
};

export type Page_StoreAdminListItem_ = {
    data: Array<StoreAdminListItem>;
    count: number;
};

export type Page_StorefrontProduct_ = {
    data: Array<StorefrontProduct>;
    count: number;
};

export type Page_StoreMemberPublic_ = {
    data: Array<StoreMemberPublic>;
    count: number;
};

export type Page_StorePublic_ = {
    data: Array<StorePublic>;
    count: number;
};

export type Page_UserPublic_ = {
    data: Array<UserPublic>;
    count: number;
};

export type Page_VariantPublic_ = {
    data: Array<VariantPublic>;
    count: number;
};

/**
 * The signed-in user and their platform roles (empty if not an admin).
 */
export type PlatformMe = {
    id: string;
    email: string;
    full_name?: (string | null);
    is_platform_admin: boolean;
    platform_roles?: Array<(string)>;
};

/**
 * A store's checkout policies (return/exchange/privacy).
 */
export type PoliciesPublic = {
    return_policy: (string | null);
    exchange_policy: (string | null);
    privacy_policy: (string | null);
};

/**
 * Partial update of a store's checkout policies.
 */
export type PoliciesUpdate = {
    return_policy?: (string | null);
    exchange_policy?: (string | null);
    privacy_policy?: (string | null);
};

/**
 * Request body for creating a user through the private endpoint.
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Fields accepted when creating a product (status starts as ``draft``).
 */
export type ProductCreate = {
    name: string;
    slug?: (string | null);
    description?: (string | null);
    price_amount_minor: number;
    price_currency?: (string | null);
    is_featured?: boolean;
    category_ids: Array<(string)>;
};

/**
 * Public representation of a product.
 */
export type ProductPublic = {
    name: string;
    slug: string;
    description?: (string | null);
    type?: ProductType;
    status?: ProductStatus;
    /**
     * Price in minor units (INV-D4)
     */
    price_amount_minor: number;
    /**
     * ISO 4217 currency code
     */
    price_currency: string;
    is_featured?: boolean;
    id: string;
    store_id: string;
};

/**
 * Lifecycle status of a catalog product (doc 09).
 *
 * - ``draft``: never published; editable; the slug follows the name.
 * - ``published``: live on the storefront; the slug is fixed.
 * - ``archived``: taken offline but kept — reversible via publish; the slug
 * stays reserved.
 *
 * Deleting a product is a **soft delete** (``deleted_at``), not a status.
 */
export type ProductStatus = 'draft' | 'published' | 'archived';

/**
 * What a product is, for the storefront and the add-to-cart gate (doc 22).
 *
 * - ``image``: a regular product (photos); may have variants; goes straight
 * to the cart.
 * - ``image_3d``: has a 3D model for viewing, but no customization; goes
 * straight to the cart.
 * - ``image_3d_customizable``: has a customizable 3D model — the customer must
 * customize and approve before adding to the cart.
 *
 * All products are ``image`` in this phase; the 3D types are activated later
 * (Fase 7), when a 3D model is generated and linked.
 */
export type ProductType = 'image' | 'image_3d' | 'image_3d_customizable';

/**
 * Partial update for a product (unset fields are left unchanged).
 */
export type ProductUpdate = {
    name?: (string | null);
    slug?: (string | null);
    description?: (string | null);
    price_amount_minor?: (number | null);
    price_currency?: (string | null);
    is_featured?: (boolean | null);
};

/**
 * Lifecycle status of a product variant.
 */
export type ProductVariantStatus = 'active' | 'archived';

/**
 * Fields accepted when creating a shipping method.
 */
export type ShippingMethodCreate = {
    type: ShippingMethodType;
    name: string;
    description?: (string | null);
    is_active?: boolean;
    price_amount_minor?: (number | null);
    min_order_amount_minor?: (number | null);
};

/**
 * Public representation of a shipping method (panel + checkout).
 */
export type ShippingMethodPublic = {
    type: ShippingMethodType;
    name: string;
    description?: (string | null);
    is_active?: boolean;
    /**
     * Flat fee (minor units) for fixed_shipping
     */
    price_amount_minor?: (number | null);
    /**
     * Minimum order (minor units) for free_shipping
     */
    min_order_amount_minor?: (number | null);
    id: string;
    store_id: string;
};

/**
 * A store's shipping/delivery option offered at checkout (doc 11).
 *
 * - ``fixed_shipping``: a flat shipping fee (``price_amount_minor``).
 * - ``free_shipping``: free, optionally above a minimum order
 * (``min_order_amount_minor``).
 * - ``local_pickup``: the customer picks the order up; no fee.
 * - ``private_delivery``: delivery arranged with the store after the purchase
 * (no automatic price/ETA — the checkout/order makes that clear).
 */
export type ShippingMethodType = 'fixed_shipping' | 'free_shipping' | 'local_pickup' | 'private_delivery';

/**
 * Partial update for a shipping method (``type`` is immutable).
 */
export type ShippingMethodUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    price_amount_minor?: (number | null);
    min_order_amount_minor?: (number | null);
};

/**
 * A store's admin detail: identity + settings + members.
 *
 * Orders/volume/webhooks/commissions are **not** included here yet — those
 * modules do not exist in the codebase yet.
 */
export type StoreAdminDetail = {
    id: string;
    name: string;
    slug: string;
    status: StoreStatus;
    created_at: string;
    settings?: (StoreSettingsPublic | null);
    members?: Array<StoreMemberPublic>;
};

/**
 * A store as listed in the platform admin (cross-store).
 */
export type StoreAdminListItem = {
    id: string;
    name: string;
    slug: string;
    status: StoreStatus;
    created_at: string;
};

/**
 * Payload to create a store. The ``country`` derives currency/locale (P3-LOC-01).
 */
export type StoreCreate = {
    name: string;
    slug?: (string | null);
    /**
     * ISO 3166-1 alpha-2
     */
    country: string;
};

/**
 * A category with its first products (templates with category sections).
 */
export type StorefrontCategorySection = {
    category: CategoryPublic;
    products: Array<StorefrontProduct>;
};

/**
 * The storefront home payload: store identity, active theme and highlights.
 */
export type StorefrontHome = {
    store: StorefrontStore;
    theme: StorefrontTheme;
    featured_products: Array<StorefrontProduct>;
    category_sections?: Array<StorefrontCategorySection>;
};

/**
 * A published product with its images, for storefront cards and detail.
 */
export type StorefrontProduct = {
    name: string;
    slug: string;
    description?: (string | null);
    type?: ProductType;
    status?: ProductStatus;
    /**
     * Price in minor units (INV-D4)
     */
    price_amount_minor: number;
    /**
     * ISO 4217 currency code
     */
    price_currency: string;
    is_featured?: boolean;
    id: string;
    store_id: string;
    images?: Array<ImagePublic>;
};

/**
 * Public store identity/contact (from ``stores``/``store_settings``).
 */
export type StorefrontStore = {
    name: string;
    slug: string;
    currency: string;
    locale: string;
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    whatsapp_number?: (string | null);
    return_policy?: (string | null);
    exchange_policy?: (string | null);
    privacy_policy?: (string | null);
};

/**
 * Public appearance for rendering (active template + theme fields + chrome).
 *
 * Read-only: a store with no settings yet falls back to the default template
 * without creating a row. ``settings`` are the active template's schema-driven
 * chrome values (defaults merged with the store's overrides).
 */
export type StorefrontTheme = {
    active_template_id: string;
    banner_image_url?: (string | null);
    headline?: (string | null);
    featured_collection_id?: (string | null);
    primary_color?: (string | null);
    background_color?: (string | null);
    font_family?: (string | null);
    settings?: {
        [key: string]: unknown;
    };
};

/**
 * Payload to invite a member by email with a role.
 */
export type StoreMemberInvite = {
    email: string;
    role: string;
};

/**
 * A store member as returned via the API.
 */
export type StoreMemberPublic = {
    id: string;
    user_id: string;
    email: string;
    role: string;
    status: MembershipStatus;
};

/**
 * Payload to change a member's role.
 */
export type StoreMemberRoleUpdate = {
    role: string;
};

/**
 * Store as returned via the API.
 */
export type StorePublic = {
    name: string;
    slug: string;
    status?: StoreStatus;
    /**
     * ISO 3166-1 alpha-2 country code
     */
    country?: string;
    /**
     * ISO 4217 currency code
     */
    currency: string;
    locale: string;
    id: string;
};

/**
 * Store settings as returned via the API.
 */
export type StoreSettingsPublic = {
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    contact_email?: (string | null);
    contact_phone?: (string | null);
    whatsapp_number?: (string | null);
    address?: (string | null);
    return_policy?: (string | null);
    exchange_policy?: (string | null);
    privacy_policy?: (string | null);
    id: string;
    store_id: string;
    social_links?: ({
    [key: string]: (string);
} | null);
};

/**
 * Editable store settings (all optional).
 */
export type StoreSettingsUpdate = {
    public_name?: (string | null);
    description?: (string | null);
    logo_url?: (string | null);
    contact_email?: (string | null);
    contact_phone?: (string | null);
    whatsapp_number?: (string | null);
    address?: (string | null);
    social_links?: ({
    [key: string]: (string);
} | null);
};

/**
 * Lifecycle status of a store (doc 09).
 *
 * - ``draft``: created, not yet published (not served on the storefront).
 * - ``active``: published/live — the only status the storefront serves.
 * - ``paused``: taken offline by the merchant (reversible via publish).
 * - ``suspended``/``blocked``: turned off by the platform admin; the
 * dashboard guard blocks access.
 *
 * Removing a store is a **soft delete** (``deleted_at``), never a status.
 */
export type StoreStatus = 'draft' | 'active' | 'paused' | 'suspended' | 'blocked';

/**
 * Public representation of a store's theme/appearance settings.
 */
export type StoreThemeSettingsPublic = {
    active_template_id: string;
    banner_image_url?: (string | null);
    headline?: (string | null);
    featured_collection_id?: (string | null);
    primary_color?: (string | null);
    background_color?: (string | null);
    font_family?: (string | null);
    id: string;
    store_id: string;
};

/**
 * A store's saved chrome overrides for a template (keyed by schema ``key``).
 */
export type TemplateSettingsPublic = {
    template_id: string;
    settings?: {
        [key: string]: unknown;
    };
};

/**
 * Patch the store's chrome overrides for the active template.
 */
export type TemplateSettingsUpdate = {
    settings: {
        [key: string]: unknown;
    };
};

/**
 * A theme template as managed in the platform admin.
 */
export type ThemeTemplateAdminPublic = {
    id: string;
    name: string;
    description?: (string | null);
    is_active: boolean;
    preview_image_url?: (string | null);
    settings_schema?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * Payload to register a theme template (its code must already exist).
 */
export type ThemeTemplateCreate = {
    id: string;
    name: string;
    description?: (string | null);
    is_active?: boolean;
    preview_image_url?: (string | null);
};

/**
 * Public representation of a global theme template (with its editable schema).
 */
export type ThemeTemplatePublic = {
    name: string;
    description?: (string | null);
    is_active?: boolean;
    preview_image_url?: (string | null);
    id: string;
    settings_schema?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * Patch payload for a theme template (unset fields are ignored).
 */
export type ThemeTemplateUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    preview_image_url?: (string | null);
};

/**
 * Partial theme update: apply a template and/or edit appearance.
 *
 * Only the fields actually sent are applied (``exclude_unset``). Setting
 * ``active_template_id`` validates the target is an available template.
 */
export type ThemeUpdate = {
    active_template_id?: (string | null);
    banner_image_url?: (string | null);
    headline?: (string | null);
    featured_collection_id?: (string | null);
};

/**
 * JSON payload containing an access token.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Set a cart line's quantity.
 */
export type UpdateItemInput = {
    quantity: number;
};

/**
 * Self password-change payload.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Payload to create an account user.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Account user as returned via the API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * Self-registration payload.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * Paginated list of account users.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Admin update payload (all fields optional).
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Self profile-update payload.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * Fields accepted when creating a product variant.
 */
export type VariantCreate = {
    name: string;
    sku?: (string | null);
    attributes?: ({
    [key: string]: (string);
} | null);
    price_override_amount_minor?: (number | null);
    price_override_currency?: (string | null);
};

/**
 * Public representation of a product variant.
 */
export type VariantPublic = {
    id: string;
    store_id: string;
    product_id: string;
    name: string;
    sku: (string | null);
    attributes: ({
    [key: string]: (string);
} | null);
    price_override_amount_minor: (number | null);
    price_override_currency: (string | null);
    status: ProductVariantStatus;
};

/**
 * Partial update for a product variant.
 */
export type VariantUpdate = {
    name?: (string | null);
    sku?: (string | null);
    attributes?: ({
    [key: string]: (string);
} | null);
    price_override_amount_minor?: (number | null);
    price_override_currency?: (string | null);
};

export type CartGetCartResponse = (CartPublic);

export type CartAddItemData = {
    requestBody: AddItemInput;
};

export type CartAddItemResponse = (CartPublic);

export type CartUpdateItemData = {
    itemId: string;
    requestBody: UpdateItemInput;
};

export type CartUpdateItemResponse = (CartPublic);

export type CartRemoveItemData = {
    itemId: string;
};

export type CartRemoveItemResponse = (CartPublic);

export type CatalogListProductsData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type CatalogListProductsResponse = (Page_ProductPublic_);

export type CatalogCreateProductData = {
    requestBody: ProductCreate;
    storeId: string;
};

export type CatalogCreateProductResponse = (ProductPublic);

export type CatalogGetProductData = {
    productId: string;
    storeId: string;
};

export type CatalogGetProductResponse = (ProductPublic);

export type CatalogUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
    storeId: string;
};

export type CatalogUpdateProductResponse = (ProductPublic);

export type CatalogDeleteProductData = {
    productId: string;
    storeId: string;
};

export type CatalogDeleteProductResponse = (void);

export type CatalogPublishProductData = {
    productId: string;
    storeId: string;
};

export type CatalogPublishProductResponse = (ProductPublic);

export type CatalogArchiveProductData = {
    productId: string;
    storeId: string;
};

export type CatalogArchiveProductResponse = (ProductPublic);

export type CatalogListCategoriesData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type CatalogListCategoriesResponse = (Page_CategoryPublic_);

export type CatalogCreateCategoryData = {
    requestBody: CategoryCreate;
    storeId: string;
};

export type CatalogCreateCategoryResponse = (CategoryPublic);

export type CatalogUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
    storeId: string;
};

export type CatalogUpdateCategoryResponse = (CategoryPublic);

export type CatalogDeleteCategoryData = {
    categoryId: string;
    storeId: string;
};

export type CatalogDeleteCategoryResponse = (void);

export type CatalogListVariantsData = {
    limit?: number;
    productId: string;
    skip?: number;
    storeId: string;
};

export type CatalogListVariantsResponse = (Page_VariantPublic_);

export type CatalogCreateVariantData = {
    productId: string;
    requestBody: VariantCreate;
    storeId: string;
};

export type CatalogCreateVariantResponse = (VariantPublic);

export type CatalogUpdateVariantData = {
    productId: string;
    requestBody: VariantUpdate;
    storeId: string;
    variantId: string;
};

export type CatalogUpdateVariantResponse = (VariantPublic);

export type CatalogDeleteVariantData = {
    productId: string;
    storeId: string;
    variantId: string;
};

export type CatalogDeleteVariantResponse = (void);

export type CatalogListImagesData = {
    productId: string;
    storeId: string;
};

export type CatalogListImagesResponse = (Array<ImagePublic>);

export type CatalogAttachImageData = {
    productId: string;
    requestBody: ImageAttach;
    storeId: string;
};

export type CatalogAttachImageResponse = (ImagePublic);

export type CatalogRemoveImageData = {
    imageId: string;
    productId: string;
    storeId: string;
};

export type CatalogRemoveImageResponse = (void);

export type CatalogGetInventoryData = {
    productId: string;
    storeId: string;
};

export type CatalogGetInventoryResponse = ((InventoryPublic | null));

export type CatalogSetInventoryData = {
    productId: string;
    requestBody: InventorySet;
    storeId: string;
};

export type CatalogSetInventoryResponse = (InventoryPublic);

export type CheckoutGetPoliciesData = {
    storeId: string;
};

export type CheckoutGetPoliciesResponse = (PoliciesPublic);

export type CheckoutUpdatePoliciesData = {
    requestBody: PoliciesUpdate;
    storeId: string;
};

export type CheckoutUpdatePoliciesResponse = (PoliciesPublic);

export type CheckoutSubmitCheckoutData = {
    requestBody: CheckoutInput;
};

export type CheckoutSubmitCheckoutResponse = (OrderPublic);

export type ContentListTemplatesData = {
    storeId: string;
};

export type ContentListTemplatesResponse = (Array<ThemeTemplatePublic>);

export type ContentGetLayoutData = {
    storeId: string;
};

export type ContentGetLayoutResponse = (StoreThemeSettingsPublic);

export type ContentUpdateLayoutData = {
    requestBody: ThemeUpdate;
    storeId: string;
};

export type ContentUpdateLayoutResponse = (StoreThemeSettingsPublic);

export type ContentGetLayoutSettingsData = {
    storeId: string;
};

export type ContentGetLayoutSettingsResponse = (TemplateSettingsPublic);

export type ContentUpdateLayoutSettingsData = {
    requestBody: TemplateSettingsUpdate;
    storeId: string;
};

export type ContentUpdateLayoutSettingsResponse = (TemplateSettingsPublic);

export type ContentResetLayoutSettingsData = {
    storeId: string;
};

export type ContentResetLayoutSettingsResponse = (TemplateSettingsPublic);

export type ContentListMyTemplatesData = {
    storeId: string;
};

export type ContentListMyTemplatesResponse = (Array<(string)>);

export type ContentListPagesData = {
    storeId: string;
};

export type ContentListPagesResponse = (Array<ContentPagePublic>);

export type ContentCreatePageData = {
    requestBody: ContentPageCreate;
    storeId: string;
};

export type ContentCreatePageResponse = (ContentPagePublic);

export type ContentUpdatePageData = {
    pageId: string;
    requestBody: ContentPageUpdate;
    storeId: string;
};

export type ContentUpdatePageResponse = (ContentPagePublic);

export type ContentDeletePageData = {
    pageId: string;
    storeId: string;
};

export type ContentDeletePageResponse = (void);

export type ContentListBannersData = {
    storeId: string;
};

export type ContentListBannersResponse = (Array<ContentBannerPublic>);

export type ContentCreateBannerData = {
    requestBody: ContentBannerCreate;
    storeId: string;
};

export type ContentCreateBannerResponse = (ContentBannerPublic);

export type ContentUpdateBannerData = {
    bannerId: string;
    requestBody: ContentBannerUpdate;
    storeId: string;
};

export type ContentUpdateBannerResponse = (ContentBannerPublic);

export type ContentDeleteBannerData = {
    bannerId: string;
    storeId: string;
};

export type ContentDeleteBannerResponse = (void);

export type ContentListMenusData = {
    storeId: string;
};

export type ContentListMenusResponse = (Array<ContentMenuPublic>);

export type ContentCreateMenuData = {
    requestBody: ContentMenuCreate;
    storeId: string;
};

export type ContentCreateMenuResponse = (ContentMenuPublic);

export type ContentUpdateMenuData = {
    menuId: string;
    requestBody: ContentMenuUpdate;
    storeId: string;
};

export type ContentUpdateMenuResponse = (ContentMenuPublic);

export type ContentDeleteMenuData = {
    menuId: string;
    storeId: string;
};

export type ContentDeleteMenuResponse = (void);

export type ContentAddMenuItemData = {
    menuId: string;
    requestBody: ContentMenuItemCreate;
    storeId: string;
};

export type ContentAddMenuItemResponse = (ContentMenuItemPublic);

export type ContentUpdateMenuItemData = {
    itemId: string;
    requestBody: ContentMenuItemUpdate;
    storeId: string;
};

export type ContentUpdateMenuItemResponse = (ContentMenuItemPublic);

export type ContentDeleteMenuItemData = {
    itemId: string;
    storeId: string;
};

export type ContentDeleteMenuItemResponse = (void);

export type HealthHealthResponse = ({
    [key: string]: (string);
});

export type HealthHealthRedisResponse = ({
    [key: string]: (string);
});

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MediaUploadMediaData = {
    formData: Body_media_upload_media;
    storeId: string;
};

export type MediaUploadMediaResponse = (MediaPublic);

export type OrdersListOrdersData = {
    limit?: number;
    skip?: number;
    status?: (OrderStatus | null);
    storeId: string;
};

export type OrdersListOrdersResponse = (Page_OrderSummary_);

export type OrdersGetOrderData = {
    orderId: string;
    storeId: string;
};

export type OrdersGetOrderResponse = (OrderDetail);

export type OrdersUpdateStatusData = {
    orderId: string;
    requestBody: OrderStatusUpdate;
    storeId: string;
};

export type OrdersUpdateStatusResponse = (OrderDetail);

export type OrdersCancelOrderData = {
    orderId: string;
    storeId: string;
};

export type OrdersCancelOrderResponse = (OrderDetail);

export type OrdersAddNoteData = {
    orderId: string;
    requestBody: OrderNoteCreate;
    storeId: string;
};

export type OrdersAddNoteResponse = (OrderNotePublic);

export type PlatformAdminGetPlatformMeResponse = (PlatformMe);

export type PlatformAdminListStoresData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type PlatformAdminListStoresResponse = (Page_StoreAdminListItem_);

export type PlatformAdminGetStoreData = {
    storeId: string;
};

export type PlatformAdminGetStoreResponse = (StoreAdminDetail);

export type PlatformAdminBlockStoreData = {
    storeId: string;
};

export type PlatformAdminBlockStoreResponse = (StoreAdminListItem);

export type PlatformAdminUnblockStoreData = {
    storeId: string;
};

export type PlatformAdminUnblockStoreResponse = (StoreAdminListItem);

export type PlatformAdminListUsersData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type PlatformAdminListUsersResponse = (Page_UserPublic_);

export type PlatformAdminGetUserData = {
    userId: string;
};

export type PlatformAdminGetUserResponse = (UserPublic);

export type PlatformAdminImpersonateUserData = {
    userId: string;
};

export type PlatformAdminImpersonateUserResponse = (Token);

export type PlatformAdminListPlansData = {
    limit?: number;
    skip?: number;
};

export type PlatformAdminListPlansResponse = (Page_BillingPlanPublic_);

export type PlatformAdminCreatePlanData = {
    requestBody: BillingPlanCreate;
};

export type PlatformAdminCreatePlanResponse = (BillingPlanPublic);

export type PlatformAdminGetPlanData = {
    planId: string;
};

export type PlatformAdminGetPlanResponse = (BillingPlanPublic);

export type PlatformAdminUpdatePlanData = {
    planId: string;
    requestBody: BillingPlanUpdate;
};

export type PlatformAdminUpdatePlanResponse = (BillingPlanPublic);

export type PlatformAdminDeletePlanData = {
    planId: string;
};

export type PlatformAdminDeletePlanResponse = (Message);

export type PlatformAdminListTemplatesResponse = (Array<ThemeTemplateAdminPublic>);

export type PlatformAdminCreateTemplateData = {
    requestBody: ThemeTemplateCreate;
};

export type PlatformAdminCreateTemplateResponse = (ThemeTemplateAdminPublic);

export type PlatformAdminGetTemplateData = {
    templateId: string;
};

export type PlatformAdminGetTemplateResponse = (ThemeTemplateAdminPublic);

export type PlatformAdminUpdateTemplateData = {
    requestBody: ThemeTemplateUpdate;
    templateId: string;
};

export type PlatformAdminUpdateTemplateResponse = (ThemeTemplateAdminPublic);

export type PlatformAdminUploadTemplateThumbnailData = {
    formData: Body_platform_admin_upload_template_thumbnail;
    templateId: string;
};

export type PlatformAdminUploadTemplateThumbnailResponse = (ThemeTemplateAdminPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ShippingListMethodsData = {
    storeId: string;
};

export type ShippingListMethodsResponse = (Array<ShippingMethodPublic>);

export type ShippingCreateMethodData = {
    requestBody: ShippingMethodCreate;
    storeId: string;
};

export type ShippingCreateMethodResponse = (ShippingMethodPublic);

export type ShippingUpdateMethodData = {
    methodId: string;
    requestBody: ShippingMethodUpdate;
    storeId: string;
};

export type ShippingUpdateMethodResponse = (ShippingMethodPublic);

export type ShippingDeleteMethodData = {
    methodId: string;
    storeId: string;
};

export type ShippingDeleteMethodResponse = (void);

export type StorefrontGetHomeResponse = (StorefrontHome);

export type StorefrontListCategoriesResponse = (Array<CategoryPublic>);

export type StorefrontListProductsData = {
    category?: (string | null);
    limit?: number;
    skip?: number;
};

export type StorefrontListProductsResponse = (Page_StorefrontProduct_);

export type StorefrontGetProductData = {
    slug: string;
};

export type StorefrontGetProductResponse = (StorefrontProduct);

export type StorefrontGetPageData = {
    slug: string;
};

export type StorefrontGetPageResponse = (ContentPagePublic);

export type StorefrontListShippingMethodsResponse = (Array<ShippingMethodPublic>);

export type StoresCreateStoreData = {
    requestBody: StoreCreate;
};

export type StoresCreateStoreResponse = (StorePublic);

export type StoresListMyStoresData = {
    limit?: number;
    skip?: number;
};

export type StoresListMyStoresResponse = (Page_StorePublic_);

export type StoresGetStoreData = {
    storeId: string;
};

export type StoresGetStoreResponse = (StorePublic);

export type StoresGetMyMembershipData = {
    storeId: string;
};

export type StoresGetMyMembershipResponse = (MyMembership);

export type StoresGetStoreSettingsData = {
    storeId: string;
};

export type StoresGetStoreSettingsResponse = (StoreSettingsPublic);

export type StoresUpdateStoreSettingsData = {
    requestBody: StoreSettingsUpdate;
    storeId: string;
};

export type StoresUpdateStoreSettingsResponse = (StoreSettingsPublic);

export type StoresPublishStoreData = {
    storeId: string;
};

export type StoresPublishStoreResponse = (StorePublic);

export type StoresPauseStoreData = {
    storeId: string;
};

export type StoresPauseStoreResponse = (StorePublic);

export type StoresListStoreMembersData = {
    limit?: number;
    skip?: number;
    storeId: string;
};

export type StoresListStoreMembersResponse = (Page_StoreMemberPublic_);

export type StoresInviteStoreMemberData = {
    requestBody: StoreMemberInvite;
    storeId: string;
};

export type StoresInviteStoreMemberResponse = (StoreMemberPublic);

export type StoresUpdateStoreMemberRoleData = {
    requestBody: StoreMemberRoleUpdate;
    storeId: string;
    userId: string;
};

export type StoresUpdateStoreMemberRoleResponse = (StoreMemberPublic);

export type StoresRemoveStoreMemberData = {
    storeId: string;
    userId: string;
};

export type StoresRemoveStoreMemberResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);