/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutUsersRouteImport } from './routes/_layout/users'
import { Route as LayoutTemplatesRouteImport } from './routes/_layout/templates'
import { Route as LayoutStoresRouteImport } from './routes/_layout/stores'
import { Route as LayoutPlansRouteImport } from './routes/_layout/plans'
import { Route as LayoutModels3dRouteImport } from './routes/_layout/models-3d'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUsersRoute = LayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTemplatesRoute = LayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStoresRoute = LayoutStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlansRoute = LayoutPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModels3dRoute = LayoutModels3dRouteImport.update({
  id: '/models-3d',
  path: '/models-3d',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/models-3d': typeof LayoutModels3dRoute
  '/plans': typeof LayoutPlansRoute
  '/stores': typeof LayoutStoresRoute
  '/templates': typeof LayoutTemplatesRoute
  '/users': typeof LayoutUsersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/models-3d': typeof LayoutModels3dRoute
  '/plans': typeof LayoutPlansRoute
  '/stores': typeof LayoutStoresRoute
  '/templates': typeof LayoutTemplatesRoute
  '/users': typeof LayoutUsersRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/models-3d': typeof LayoutModels3dRoute
  '/_layout/plans': typeof LayoutPlansRoute
  '/_layout/stores': typeof LayoutStoresRoute
  '/_layout/templates': typeof LayoutTemplatesRoute
  '/_layout/users': typeof LayoutUsersRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/models-3d'
    | '/plans'
    | '/stores'
    | '/templates'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/models-3d'
    | '/plans'
    | '/stores'
    | '/templates'
    | '/users'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/models-3d'
    | '/_layout/plans'
    | '/_layout/stores'
    | '/_layout/templates'
    | '/_layout/users'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/users': {
      id: '/_layout/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof LayoutUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/templates': {
      id: '/_layout/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof LayoutTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stores': {
      id: '/_layout/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof LayoutStoresRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plans': {
      id: '/_layout/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof LayoutPlansRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models-3d': {
      id: '/_layout/models-3d'
      path: '/models-3d'
      fullPath: '/models-3d'
      preLoaderRoute: typeof LayoutModels3dRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutModels3dRoute: typeof LayoutModels3dRoute
  LayoutPlansRoute: typeof LayoutPlansRoute
  LayoutStoresRoute: typeof LayoutStoresRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutUsersRoute: typeof LayoutUsersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutModels3dRoute: LayoutModels3dRoute,
  LayoutPlansRoute: LayoutPlansRoute,
  LayoutStoresRoute: LayoutStoresRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutUsersRoute: LayoutUsersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
